-- ============================================================
-- MIGRACAO 004 - CORRIGE ESTRUTURA DE TABELAS E APLICA RLS
-- ============================================================

-- ------------------------------------------------------------
-- 1. RECRIAR TABELA notifications (estava errada: PK=cep, sem id/created_at)
-- ------------------------------------------------------------
DROP TABLE IF EXISTS public.notifications CASCADE;

CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep TEXT NOT NULL,
    category TEXT NOT NULL
        CHECK (category IN ('Avisos', 'Reservas', 'Assembleias', 'Entregas')),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT notifications_cep_fkey
        FOREIGN KEY (cep)
        REFERENCES public.condominiums (cep)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notifications_cep ON public.notifications(cep);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at DESC);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS notifications_select_policy ON public.notifications;
CREATE POLICY notifications_select_policy ON public.notifications
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = notifications.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = notifications.cep
                  OR u.condominium->>'condominium_id' = notifications.cep))
        )
    )
);

DROP POLICY IF EXISTS notifications_insert_policy ON public.notifications;
CREATE POLICY notifications_insert_policy ON public.notifications
FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = notifications.cep
                  OR u.condominium->>'condominium_id' = notifications.cep))
        )
    )
    OR EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = notifications.cep
    )
);

DROP POLICY IF EXISTS notifications_update_policy ON public.notifications;
CREATE POLICY notifications_update_policy ON public.notifications
FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND u.user_type = 'sindico'
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = notifications.cep
                  OR u.condominium->>'condominium_id' = notifications.cep))
        )
    )
    OR EXISTS (
        SELECT 1 FROM user_condominiums uc
        JOIN users u ON u.email = uc.user_email
        WHERE uc.user_email = auth.email()
        AND u.user_type = 'sindico'
        AND uc.condominium_id = notifications.cep
    )
) WITH CHECK (
    EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND u.user_type = 'sindico'
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = notifications.cep
                  OR u.condominium->>'condominium_id' = notifications.cep))
        )
    )
    OR EXISTS (
        SELECT 1 FROM user_condominiums uc
        JOIN users u ON u.email = uc.user_email
        WHERE uc.user_email = auth.email()
        AND u.user_type = 'sindico'
        AND uc.condominium_id = notifications.cep
    )
);

DROP POLICY IF EXISTS notifications_delete_policy ON public.notifications;
CREATE POLICY notifications_delete_policy ON public.notifications
FOR DELETE USING (
    EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND u.user_type = 'sindico'
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = notifications.cep
                  OR u.condominium->>'condominium_id' = notifications.cep))
        )
    )
    OR EXISTS (
        SELECT 1 FROM user_condominiums uc
        JOIN users u ON u.email = uc.user_email
        WHERE uc.user_email = auth.email()
        AND u.user_type = 'sindico'
        AND uc.condominium_id = notifications.cep
    )
);

-- ------------------------------------------------------------
-- 2. RECRIAR TABELA marketplace_items (estava errada: PK=cep, sem id/created_at)
-- ------------------------------------------------------------
DROP TABLE IF EXISTS public.marketplace_items CASCADE;

CREATE TABLE public.marketplace_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep TEXT NOT NULL,
    user_name TEXT NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL
        CHECK (category IN ('Móveis', 'Eletrodomésticos', 'Eletrônicos', 'Infantil', 'Esportes', 'Livros', 'Outros')),
    price NUMERIC(10, 2) NOT NULL
        CHECK (price >= 0),
    description TEXT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT marketplace_items_cep_fkey
        FOREIGN KEY (cep)
        REFERENCES public.condominiums (cep)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_marketplace_items_cep ON public.marketplace_items(cep);
CREATE INDEX IF NOT EXISTS idx_marketplace_items_category ON public.marketplace_items(category);
CREATE INDEX IF NOT EXISTS idx_marketplace_items_created_at ON public.marketplace_items(created_at DESC);

ALTER TABLE public.marketplace_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS marketplace_items_select_policy ON public.marketplace_items;
CREATE POLICY marketplace_items_select_policy ON public.marketplace_items
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = marketplace_items.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = marketplace_items.cep
                  OR u.condominium->>'condominium_id' = marketplace_items.cep))
        )
    )
);

DROP POLICY IF EXISTS marketplace_items_insert_policy ON public.marketplace_items;
CREATE POLICY marketplace_items_insert_policy ON public.marketplace_items
FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = marketplace_items.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = marketplace_items.cep
                  OR u.condominium->>'condominium_id' = marketplace_items.cep))
        )
    )
);

DROP POLICY IF EXISTS marketplace_items_update_policy ON public.marketplace_items;
CREATE POLICY marketplace_items_update_policy ON public.marketplace_items
FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = marketplace_items.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = marketplace_items.cep
                  OR u.condominium->>'condominium_id' = marketplace_items.cep))
        )
    )
) WITH CHECK (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = marketplace_items.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = marketplace_items.cep
                  OR u.condominium->>'condominium_id' = marketplace_items.cep))
        )
    )
);

DROP POLICY IF EXISTS marketplace_items_delete_policy ON public.marketplace_items;
CREATE POLICY marketplace_items_delete_policy ON public.marketplace_items
FOR DELETE USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = marketplace_items.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = marketplace_items.cep
                  OR u.condominium->>'condominium_id' = marketplace_items.cep))
        )
    )
);

-- ------------------------------------------------------------
-- 3. GARANTIR lost_and_found_items RLS policies
-- ------------------------------------------------------------
ALTER TABLE public.lost_and_found_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS lost_and_found_items_select_policy ON public.lost_and_found_items;
CREATE POLICY lost_and_found_items_select_policy ON public.lost_and_found_items
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = lost_and_found_items.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = lost_and_found_items.cep
                  OR u.condominium->>'condominium_id' = lost_and_found_items.cep))
        )
    )
);

DROP POLICY IF EXISTS lost_and_found_items_insert_policy ON public.lost_and_found_items;
CREATE POLICY lost_and_found_items_insert_policy ON public.lost_and_found_items
FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = lost_and_found_items.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = lost_and_found_items.cep
                  OR u.condominium->>'condominium_id' = lost_and_found_items.cep))
        )
    )
);

DROP POLICY IF EXISTS lost_and_found_items_update_policy ON public.lost_and_found_items;
CREATE POLICY lost_and_found_items_update_policy ON public.lost_and_found_items
FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND u.user_type = 'sindico'
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = lost_and_found_items.cep
                  OR u.condominium->>'condominium_id' = lost_and_found_items.cep))
        )
    )
    OR EXISTS (
        SELECT 1 FROM user_condominiums uc
        JOIN users u ON u.email = uc.user_email
        WHERE uc.user_email = auth.email()
        AND u.user_type = 'sindico'
        AND uc.condominium_id = lost_and_found_items.cep
    )
) WITH CHECK (
    EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND u.user_type = 'sindico'
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = lost_and_found_items.cep
                  OR u.condominium->>'condominium_id' = lost_and_found_items.cep))
        )
    )
    OR EXISTS (
        SELECT 1 FROM user_condominiums uc
        JOIN users u ON u.email = uc.user_email
        WHERE uc.user_email = auth.email()
        AND u.user_type = 'sindico'
        AND uc.condominium_id = lost_and_found_items.cep
    )
);

DROP POLICY IF EXISTS lost_and_found_items_delete_policy ON public.lost_and_found_items;
CREATE POLICY lost_and_found_items_delete_policy ON public.lost_and_found_items
FOR DELETE USING (
    EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND u.user_type = 'sindico'
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = lost_and_found_items.cep
                  OR u.condominium->>'condominium_id' = lost_and_found_items.cep))
        )
    )
    OR EXISTS (
        SELECT 1 FROM user_condominiums uc
        JOIN users u ON u.email = uc.user_email
        WHERE uc.user_email = auth.email()
        AND u.user_type = 'sindico'
        AND uc.condominium_id = lost_and_found_items.cep
    )
);

-- ------------------------------------------------------------
-- 4. GARANTIR service_providers RLS policies
-- ------------------------------------------------------------
ALTER TABLE public.service_providers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS service_providers_select_policy ON public.service_providers;
CREATE POLICY service_providers_select_policy ON public.service_providers
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = service_providers.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = service_providers.cep
                  OR u.condominium->>'condominium_id' = service_providers.cep))
        )
    )
);

DROP POLICY IF EXISTS service_providers_insert_policy ON public.service_providers;
CREATE POLICY service_providers_insert_policy ON public.service_providers
FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = service_providers.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = service_providers.cep
                  OR u.condominium->>'condominium_id' = service_providers.cep))
        )
    )
);

DROP POLICY IF EXISTS service_providers_update_policy ON public.service_providers;
CREATE POLICY service_providers_update_policy ON public.service_providers
FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = service_providers.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = service_providers.cep
                  OR u.condominium->>'condominium_id' = service_providers.cep))
        )
    )
) WITH CHECK (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = service_providers.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = service_providers.cep
                  OR u.condominium->>'condominium_id' = service_providers.cep))
        )
    )
);

DROP POLICY IF EXISTS service_providers_delete_policy ON public.service_providers;
CREATE POLICY service_providers_delete_policy ON public.service_providers
FOR DELETE USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = service_providers.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = service_providers.cep
                  OR u.condominium->>'condominium_id' = service_providers.cep))
        )
    )
);

-- ============================================================
-- CORRECAO DE POLITICAS RLS - PROBLEMAS REPORTADOS
-- ============================================================

-- ------------------------------------------------------------
-- CORRECAO: assembly_chat_messages RLS
-- ------------------------------------------------------------
ALTER TABLE public.assembly_chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS assembly_chat_messages_select_policy ON public.assembly_chat_messages;
CREATE POLICY assembly_chat_messages_select_policy ON public.assembly_chat_messages
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = assembly_chat_messages.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = assembly_chat_messages.cep
                  OR u.condominium->>'condominium_id' = assembly_chat_messages.cep))
        )
    )
    OR assembly_chat_messages.user_email = auth.email()
);

DROP POLICY IF EXISTS assembly_chat_messages_insert_policy ON public.assembly_chat_messages;
CREATE POLICY assembly_chat_messages_insert_policy ON public.assembly_chat_messages
FOR INSERT WITH CHECK (
    assembly_chat_messages.user_email = auth.email()
    AND (
        EXISTS (
            SELECT 1 FROM user_condominiums uc
            WHERE uc.user_email = auth.email()
            AND uc.condominium_id = assembly_chat_messages.cep
        )
        OR EXISTS (
            SELECT 1 FROM users u
            WHERE u.email = auth.email()
            AND (
                (jsonb_typeof(u.condominium) = 'object'
                 AND (u.condominium->>'cep' = assembly_chat_messages.cep
                      OR u.condominium->>'condominium_id' = assembly_chat_messages.cep))
            )
        )
    )
);

DROP POLICY IF EXISTS assembly_chat_messages_update_policy ON public.assembly_chat_messages;
CREATE POLICY assembly_chat_messages_update_policy ON public.assembly_chat_messages
FOR UPDATE USING (
    assembly_chat_messages.user_email = auth.email()
    OR EXISTS (
        SELECT 1 FROM scheduled_assemblies sa
        WHERE sa.id = assembly_chat_messages.assembly_id
        AND sa.created_by = auth.email()
    )
) WITH CHECK (
    assembly_chat_messages.user_email = auth.email()
    OR EXISTS (
        SELECT 1 FROM scheduled_assemblies sa
        WHERE sa.id = assembly_chat_messages.assembly_id
        AND sa.created_by = auth.email()
    )
);

-- ------------------------------------------------------------
-- CORRECAO: assembly_speaking_requests RLS
-- ------------------------------------------------------------
ALTER TABLE public.assembly_speaking_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS assembly_speaking_requests_select_policy ON public.assembly_speaking_requests;
CREATE POLICY assembly_speaking_requests_select_policy ON public.assembly_speaking_requests
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM user_condominiums uc
        WHERE uc.user_email = auth.email()
        AND uc.condominium_id = assembly_speaking_requests.cep
    )
    OR EXISTS (
        SELECT 1 FROM users u
        WHERE u.email = auth.email()
        AND (
            (jsonb_typeof(u.condominium) = 'object'
             AND (u.condominium->>'cep' = assembly_speaking_requests.cep
                  OR u.condominium->>'condominium_id' = assembly_speaking_requests.cep))
        )
    )
    OR assembly_speaking_requests.user_email = auth.email()
);

DROP POLICY IF EXISTS assembly_speaking_requests_insert_policy ON public.assembly_speaking_requests;
CREATE POLICY assembly_speaking_requests_insert_policy ON public.assembly_speaking_requests
FOR INSERT WITH CHECK (
    assembly_speaking_requests.user_email = auth.email()
    AND (
        EXISTS (
            SELECT 1 FROM user_condominiums uc
            WHERE uc.user_email = auth.email()
            AND uc.condominium_id = assembly_speaking_requests.cep
        )
        OR EXISTS (
            SELECT 1 FROM users u
            WHERE u.email = auth.email()
            AND (
                (jsonb_typeof(u.condominium) = 'object'
                 AND (u.condominium->>'cep' = assembly_speaking_requests.cep
                      OR u.condominium->>'condominium_id' = assembly_speaking_requests.cep))
            )
        )
    )
);

DROP POLICY IF EXISTS assembly_speaking_requests_update_policy ON public.assembly_speaking_requests;
CREATE POLICY assembly_speaking_requests_update_policy ON public.assembly_speaking_requests
FOR UPDATE USING (
    assembly_speaking_requests.user_email = auth.email()
    OR EXISTS (
        SELECT 1 FROM scheduled_assemblies sa
        WHERE sa.id = assembly_speaking_requests.assembly_id
        AND sa.created_by = auth.email()
    )
) WITH CHECK (
    assembly_speaking_requests.user_email = auth.email()
    OR EXISTS (
        SELECT 1 FROM scheduled_assemblies sa
        WHERE sa.id = assembly_speaking_requests.assembly_id
        AND sa.created_by = auth.email()
    )
);

-- ------------------------------------------------------------
-- CORRECAO: visitors RLS
-- ------------------------------------------------------------
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'visitors'
    ) THEN
        ALTER TABLE public.visitors ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS visitors_select_policy ON public.visitors;
        CREATE POLICY visitors_select_policy ON public.visitors
        FOR SELECT USING (
            EXISTS (
                SELECT 1 FROM users u
                WHERE u.email = auth.email()
                AND (
                    (jsonb_typeof(u.condominium) = 'object'
                     AND (u.condominium->>'cep' IS NOT NULL
                          OR u.condominium->>'condominium_id' IS NOT NULL))
                )
            )
            OR EXISTS (
                SELECT 1 FROM user_condominiums uc
                WHERE uc.user_email = auth.email()
            )
            OR visitors.responsible_cpf IN (
                SELECT REPLACE(COALESCE(u2.cpf, ''), '.', '') FROM users u2 WHERE u2.email = auth.email()
            )
        );

        DROP POLICY IF EXISTS visitors_insert_policy ON public.visitors;
        CREATE POLICY visitors_insert_policy ON public.visitors
        FOR INSERT WITH CHECK (
            EXISTS (
                SELECT 1 FROM users u
                WHERE u.email = auth.email()
                AND (
                    (jsonb_typeof(u.condominium) = 'object'
                     AND (u.condominium->>'cep' IS NOT NULL
                          OR u.condominium->>'condominium_id' IS NOT NULL))
                    OR u.user_type IN ('sindico', 'porteiro', 'morador')
                )
            )
            OR EXISTS (
                SELECT 1 FROM user_condominiums uc
                WHERE uc.user_email = auth.email()
            )
        );

        DROP POLICY IF EXISTS visitors_update_policy ON public.visitors;
        CREATE POLICY visitors_update_policy ON public.visitors
        FOR UPDATE USING (
            EXISTS (
                SELECT 1 FROM users u
                WHERE u.email = auth.email()
                AND u.user_type IN ('sindico', 'porteiro')
            )
            OR visitors.responsible_cpf IN (
                SELECT REPLACE(COALESCE(u2.cpf, ''), '.', '') FROM users u2 WHERE u2.email = auth.email()
            )
        ) WITH CHECK (
            EXISTS (
                SELECT 1 FROM users u
                WHERE u.email = auth.email()
                AND u.user_type IN ('sindico', 'porteiro')
            )
            OR visitors.responsible_cpf IN (
                SELECT REPLACE(COALESCE(u2.cpf, ''), '.', '') FROM users u2 WHERE u2.email = auth.email()
            )
        );

        DROP POLICY IF EXISTS visitors_delete_policy ON public.visitors;
        CREATE POLICY visitors_delete_policy ON public.visitors
        FOR DELETE USING (
            EXISTS (
                SELECT 1 FROM users u
                WHERE u.email = auth.email()
                AND u.user_type IN ('sindico', 'porteiro')
            )
        );
    END IF;
END $$;
