-- ============================================================
-- MIGRAÇÃO 006
-- CORREÇÕES DE RLS + MARKETPLACE + ACHADOS E PERDIDOS
-- Condomit
-- ============================================================


-- ============================================================
-- 0. TABELAS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.marketplace_items (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    cep TEXT NOT NULL,

    user_name TEXT NOT NULL,

    title TEXT NOT NULL,

    category TEXT NOT NULL
        CHECK (
            category IN (
                'Móveis',
                'Eletrodomésticos',
                'Eletrônicos',
                'Infantil',
                'Esportes',
                'Livros',
                'Outros'
            )
        ),

    price NUMERIC(10, 2)
        NOT NULL
        CHECK (price >= 0),

    description TEXT NOT NULL,

    image_url TEXT NOT NULL,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    CONSTRAINT marketplace_items_cep_fkey
        FOREIGN KEY (cep)
        REFERENCES public.condominiums (cep)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS public.lost_and_found_items (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    cep TEXT NOT NULL,

    item_type TEXT NOT NULL
        CHECK (
            item_type IN (
                'Encontrado',
                'Perdido'
            )
        ),

    item_name TEXT NOT NULL,

    location TEXT NOT NULL,

    item_date DATE NOT NULL,

    image_url TEXT NOT NULL,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    CONSTRAINT lost_and_found_items_cep_fkey
        FOREIGN KEY (cep)
        REFERENCES public.condominiums (cep)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- ============================================================
-- 0.1 ÍNDICES
-- ============================================================

CREATE INDEX IF NOT EXISTS
idx_marketplace_items_cep
ON public.marketplace_items (cep);


CREATE INDEX IF NOT EXISTS
idx_marketplace_items_created_at
ON public.marketplace_items (created_at DESC);


CREATE INDEX IF NOT EXISTS
idx_lost_and_found_items_cep
ON public.lost_and_found_items (cep);


CREATE INDEX IF NOT EXISTS
idx_lost_and_found_items_date
ON public.lost_and_found_items (item_date DESC);


-- ============================================================
-- 0.2 VISITORS
-- Garante que a coluna CEP exista
-- ============================================================

ALTER TABLE IF EXISTS public.visitors
ADD COLUMN IF NOT EXISTS cep TEXT;


-- Garante FK do CEP de visitors
DO $$
BEGIN

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
        AND table_name = 'visitors'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'public'
        AND constraint_name = 'visitors_cep_fkey'
    )
    THEN

        BEGIN

            ALTER TABLE public.visitors
            ADD CONSTRAINT visitors_cep_fkey
            FOREIGN KEY (cep)
            REFERENCES public.condominiums (cep)
            ON UPDATE CASCADE
            ON DELETE SET NULL;

        EXCEPTION
            WHEN duplicate_object THEN
                NULL;

            WHEN OTHERS THEN
                RAISE NOTICE
                'Não foi possível criar visitors_cep_fkey: %',
                SQLERRM;
        END;

    END IF;

END
$$;


-- ============================================================
-- 1. HELPERS DE RLS
-- ============================================================


-- ------------------------------------------------------------
-- 1.1 E-mail do usuário autenticado
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.condomit_auth_email()
RETURNS TEXT
LANGUAGE sql
STABLE
AS $$
    SELECT LOWER(
        COALESCE(
            auth.jwt() ->> 'email',
            ''
        )
    );
$$;


-- ------------------------------------------------------------
-- 1.2 Comparar CEP
--
-- Permite comparar:
-- 04284-070
-- com
-- 04284070
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.condomit_same_cep(
    a TEXT,
    b TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
AS $$

    SELECT

        NULLIF(
            REGEXP_REPLACE(
                COALESCE(a, ''),
                '\D',
                '',
                'g'
            ),
            ''
        ) IS NOT NULL

        AND

        REGEXP_REPLACE(
            COALESCE(a, ''),
            '\D',
            '',
            'g'
        )

        =

        REGEXP_REPLACE(
            COALESCE(b, ''),
            '\D',
            '',
            'g'
        );

$$;


-- ------------------------------------------------------------
-- 1.3 Verificar se usuário pertence ao condomínio
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION
public.condomit_user_belongs_to_cep(
    target_cep TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$

    SELECT

        public.condomit_auth_email() <> ''

        AND

        (

            -- ----------------------------------------------
            -- Tenta primeiro user_condominiums
            -- ----------------------------------------------

            EXISTS (

                SELECT 1

                FROM public.user_condominiums uc

                WHERE

                    LOWER(
                        COALESCE(
                            uc.user_email,
                            ''
                        )
                    )
                    =
                    public.condomit_auth_email()

                    AND

                    public.condomit_same_cep(
                        uc.condominium_id,
                        target_cep
                    )

            )


            OR


            -- ----------------------------------------------
            -- Fallback:
            -- campo condominium JSONB da tabela users
            -- ----------------------------------------------

            EXISTS (

                SELECT 1

                FROM public.users u

                WHERE

                    LOWER(
                        COALESCE(
                            u.email,
                            ''
                        )
                    )
                    =
                    public.condomit_auth_email()

                    AND

                    jsonb_typeof(
                        u.condominium
                    ) = 'object'

                    AND (

                        public.condomit_same_cep(
                            u.condominium ->> 'cep',
                            target_cep
                        )

                        OR

                        public.condomit_same_cep(
                            u.condominium ->> 'condominium_id',
                            target_cep
                        )

                    )

            )

        );

$$;


-- ------------------------------------------------------------
-- 1.4 Tipo do usuário autenticado
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION
public.condomit_current_user_type()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$

    SELECT LOWER(
        COALESCE(
            (
                SELECT u.user_type

                FROM public.users u

                WHERE
                    LOWER(
                        COALESCE(
                            u.email,
                            ''
                        )
                    )
                    =
                    public.condomit_auth_email()

                LIMIT 1
            ),
            ''
        )
    );

$$;


-- ------------------------------------------------------------
-- 1.5 CPF do usuário autenticado
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION
public.condomit_current_user_cpf()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$

    SELECT REGEXP_REPLACE(

        COALESCE(
            (
                SELECT u.cpf

                FROM public.users u

                WHERE
                    LOWER(
                        COALESCE(
                            u.email,
                            ''
                        )
                    )
                    =
                    public.condomit_auth_email()

                LIMIT 1
            ),
            ''
        ),

        '\D',
        '',
        'g'

    );

$$;


-- ============================================================
-- 1.6 PERMISSÕES DOS HELPERS
-- ============================================================

REVOKE ALL
ON FUNCTION public.condomit_user_belongs_to_cep(TEXT)
FROM PUBLIC;


REVOKE ALL
ON FUNCTION public.condomit_current_user_type()
FROM PUBLIC;


REVOKE ALL
ON FUNCTION public.condomit_current_user_cpf()
FROM PUBLIC;


GRANT EXECUTE
ON FUNCTION public.condomit_user_belongs_to_cep(TEXT)
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.condomit_current_user_type()
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.condomit_current_user_cpf()
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.condomit_auth_email()
TO authenticated;


GRANT EXECUTE
ON FUNCTION public.condomit_same_cep(TEXT, TEXT)
TO authenticated;



-- ============================================================
-- 2. CHAT DA ASSEMBLEIA
-- assembly_chat_messages
-- ============================================================

ALTER TABLE IF EXISTS
public.assembly_chat_messages
ENABLE ROW LEVEL SECURITY;


-- Remove versões anteriores
DROP POLICY IF EXISTS
assembly_chat_messages_select_policy
ON public.assembly_chat_messages;


DROP POLICY IF EXISTS
assembly_chat_messages_insert_policy
ON public.assembly_chat_messages;


DROP POLICY IF EXISTS
assembly_chat_messages_update_policy
ON public.assembly_chat_messages;


DROP POLICY IF EXISTS
assembly_chat_messages_delete_policy
ON public.assembly_chat_messages;


-- ------------------------------------------------------------
-- SELECT
-- ------------------------------------------------------------

CREATE POLICY
assembly_chat_messages_select_policy
ON public.assembly_chat_messages
FOR SELECT
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        assembly_chat_messages.cep
    )

);


-- ------------------------------------------------------------
-- INSERT
-- Corrige:
-- new row violates row-level security policy
-- ------------------------------------------------------------

CREATE POLICY
assembly_chat_messages_insert_policy
ON public.assembly_chat_messages
FOR INSERT
TO authenticated
WITH CHECK (

    -- Precisa ter usuário autenticado
    public.condomit_auth_email() <> ''

    AND

    -- O usuário só pode enviar mensagem
    -- utilizando o próprio e-mail
    LOWER(
        COALESCE(
            assembly_chat_messages.user_email,
            ''
        )
    )
    =
    public.condomit_auth_email()

    AND

    -- Precisa pertencer ao condomínio
    public.condomit_user_belongs_to_cep(
        assembly_chat_messages.cep
    )

    AND

    -- Assembleia precisa existir
    AND EXISTS (

        SELECT 1

        FROM public.scheduled_assemblies sa

        WHERE

            sa.id =
                assembly_chat_messages.assembly_id

            AND

            public.condomit_same_cep(
                sa.cep,
                assembly_chat_messages.cep
            )

            AND

            sa.status IN (
                'agendada',
                'em_andamento'
            )

    )

);


-- ------------------------------------------------------------
-- UPDATE
-- ------------------------------------------------------------

CREATE POLICY
assembly_chat_messages_update_policy
ON public.assembly_chat_messages
FOR UPDATE
TO authenticated
USING (

    LOWER(
        COALESCE(
            assembly_chat_messages.user_email,
            ''
        )
    )
    =
    public.condomit_auth_email()

    OR

    EXISTS (

        SELECT 1

        FROM public.scheduled_assemblies sa

        WHERE

            sa.id =
                assembly_chat_messages.assembly_id

            AND

            LOWER(
                COALESCE(
                    sa.created_by,
                    ''
                )
            )
            =
            public.condomit_auth_email()

    )

)
WITH CHECK (

    LOWER(
        COALESCE(
            assembly_chat_messages.user_email,
            ''
        )
    )
    =
    public.condomit_auth_email()

    OR

    EXISTS (

        SELECT 1

        FROM public.scheduled_assemblies sa

        WHERE

            sa.id =
                assembly_chat_messages.assembly_id

            AND

            LOWER(
                COALESCE(
                    sa.created_by,
                    ''
                )
            )
            =
            public.condomit_auth_email()

    )

);


-- ------------------------------------------------------------
-- DELETE
-- O autor ou organizador pode apagar
-- ------------------------------------------------------------

CREATE POLICY
assembly_chat_messages_delete_policy
ON public.assembly_chat_messages
FOR DELETE
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        assembly_chat_messages.cep
    )

    AND (

        LOWER(
            COALESCE(
                assembly_chat_messages.user_email,
                ''
            )
        )
        =
        public.condomit_auth_email()

        OR

        EXISTS (

            SELECT 1

            FROM public.scheduled_assemblies sa

            WHERE

                sa.id =
                    assembly_chat_messages.assembly_id

                AND

                LOWER(
                    COALESCE(
                        sa.created_by,
                        ''
                    )
                )
                =
                public.condomit_auth_email()

        )

    )

);



-- ============================================================
-- 3. VOTAÇÕES
-- ============================================================

ALTER TABLE IF EXISTS
public.assembly_polls
ENABLE ROW LEVEL SECURITY;


ALTER TABLE IF EXISTS
public.assembly_poll_options
ENABLE ROW LEVEL SECURITY;


ALTER TABLE IF EXISTS
public.assembly_votes
ENABLE ROW LEVEL SECURITY;



-- ============================================================
-- 3.1 ASSEMBLY_POLLS
-- ============================================================

DROP POLICY IF EXISTS
assembly_polls_select_policy
ON public.assembly_polls;


DROP POLICY IF EXISTS
assembly_polls_insert_policy
ON public.assembly_polls;


DROP POLICY IF EXISTS
assembly_polls_update_policy
ON public.assembly_polls;


DROP POLICY IF EXISTS
assembly_polls_delete_policy
ON public.assembly_polls;


-- SELECT

CREATE POLICY
assembly_polls_select_policy
ON public.assembly_polls
FOR SELECT
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        assembly_polls.cep
    )

);


-- INSERT

CREATE POLICY
assembly_polls_insert_policy
ON public.assembly_polls
FOR INSERT
TO authenticated
WITH CHECK (

    public.condomit_auth_email() <> ''

    AND

    LOWER(
        COALESCE(
            assembly_polls.created_by,
            ''
        )
    )
    =
    public.condomit_auth_email()

    AND

    public.condomit_user_belongs_to_cep(
        assembly_polls.cep
    )

    AND

    EXISTS (

        SELECT 1

        FROM public.scheduled_assemblies sa

        WHERE

            sa.id =
                assembly_polls.assembly_id

            AND

            public.condomit_same_cep(
                sa.cep,
                assembly_polls.cep
            )

            AND (

                LOWER(
                    COALESCE(
                        sa.created_by,
                        ''
                    )
                )
                =
                public.condomit_auth_email()

                OR

                public.condomit_current_user_type()
                IN (
                    'sindico',
                    'síndico',
                    'admin'
                )

            )

    )

);


-- UPDATE

CREATE POLICY
assembly_polls_update_policy
ON public.assembly_polls
FOR UPDATE
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        assembly_polls.cep
    )

    AND (

        LOWER(
            COALESCE(
                assembly_polls.created_by,
                ''
            )
        )
        =
        public.condomit_auth_email()

        OR

        public.condomit_current_user_type()
        IN (
            'sindico',
            'síndico',
            'admin'
        )

    )

)
WITH CHECK (

    public.condomit_user_belongs_to_cep(
        assembly_polls.cep
    )

    AND (

        LOWER(
            COALESCE(
                assembly_polls.created_by,
                ''
            )
        )
        =
        public.condomit_auth_email()

        OR

        public.condomit_current_user_type()
        IN (
            'sindico',
            'síndico',
            'admin'
        )

    )

);


-- DELETE

CREATE POLICY
assembly_polls_delete_policy
ON public.assembly_polls
FOR DELETE
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        assembly_polls.cep
    )

    AND (

        LOWER(
            COALESCE(
                assembly_polls.created_by,
                ''
            )
        )
        =
        public.condomit_auth_email()

        OR

        public.condomit_current_user_type()
        IN (
            'sindico',
            'síndico',
            'admin'
        )

    )

);



-- ============================================================
-- 3.2 OPÇÕES DAS VOTAÇÕES
-- assembly_poll_options
-- ============================================================

DROP POLICY IF EXISTS
assembly_poll_options_policy
ON public.assembly_poll_options;


DROP POLICY IF EXISTS
assembly_poll_options_select_policy
ON public.assembly_poll_options;


DROP POLICY IF EXISTS
assembly_poll_options_insert_policy
ON public.assembly_poll_options;


DROP POLICY IF EXISTS
assembly_poll_options_update_policy
ON public.assembly_poll_options;


DROP POLICY IF EXISTS
assembly_poll_options_delete_policy
ON public.assembly_poll_options;


-- SELECT

CREATE POLICY
assembly_poll_options_select_policy
ON public.assembly_poll_options
FOR SELECT
TO authenticated
USING (

    EXISTS (

        SELECT 1

        FROM public.assembly_polls ap

        WHERE

            ap.id =
                assembly_poll_options.poll_id

            AND

            public.condomit_user_belongs_to_cep(
                ap.cep
            )

    )

);


-- INSERT

CREATE POLICY
assembly_poll_options_insert_policy
ON public.assembly_poll_options
FOR INSERT
TO authenticated
WITH CHECK (

    EXISTS (

        SELECT 1

        FROM public.assembly_polls ap

        WHERE

            ap.id =
                assembly_poll_options.poll_id

            AND

            public.condomit_same_cep(
                ap.cep,
                assembly_poll_options.cep
            )

            AND

            public.condomit_user_belongs_to_cep(
                ap.cep
            )

            AND (

                LOWER(
                    COALESCE(
                        ap.created_by,
                        ''
                    )
                )
                =
                public.condomit_auth_email()

                OR

                public.condomit_current_user_type()
                IN (
                    'sindico',
                    'síndico',
                    'admin'
                )

            )

    )

);


-- UPDATE

CREATE POLICY
assembly_poll_options_update_policy
ON public.assembly_poll_options
FOR UPDATE
TO authenticated
USING (

    EXISTS (

        SELECT 1

        FROM public.assembly_polls ap

        WHERE

            ap.id =
                assembly_poll_options.poll_id

            AND

            public.condomit_user_belongs_to_cep(
                ap.cep
            )

            AND (

                LOWER(
                    COALESCE(
                        ap.created_by,
                        ''
                    )
                )
                =
                public.condomit_auth_email()

                OR

                public.condomit_current_user_type()
                IN (
                    'sindico',
                    'síndico',
                    'admin'
                )

            )

    )

)
WITH CHECK (

    EXISTS (

        SELECT 1

        FROM public.assembly_polls ap

        WHERE

            ap.id =
                assembly_poll_options.poll_id

            AND

            public.condomit_same_cep(
                ap.cep,
                assembly_poll_options.cep
            )

            AND

            public.condomit_user_belongs_to_cep(
                ap.cep
            )

            AND (

                LOWER(
                    COALESCE(
                        ap.created_by,
                        ''
                    )
                )
                =
                public.condomit_auth_email()

                OR

                public.condomit_current_user_type()
                IN (
                    'sindico',
                    'síndico',
                    'admin'
                )

            )

    )

);


-- DELETE

CREATE POLICY
assembly_poll_options_delete_policy
ON public.assembly_poll_options
FOR DELETE
TO authenticated
USING (

    EXISTS (

        SELECT 1

        FROM public.assembly_polls ap

        WHERE

            ap.id =
                assembly_poll_options.poll_id

            AND

            public.condomit_user_belongs_to_cep(
                ap.cep
            )

            AND (

                LOWER(
                    COALESCE(
                        ap.created_by,
                        ''
                    )
                )
                =
                public.condomit_auth_email()

                OR

                public.condomit_current_user_type()
                IN (
                    'sindico',
                    'síndico',
                    'admin'
                )

            )

    )

);



-- ============================================================
-- 3.3 VOTOS
-- assembly_votes
-- ============================================================

DROP POLICY IF EXISTS
assembly_votes_select_policy
ON public.assembly_votes;


DROP POLICY IF EXISTS
assembly_votes_insert_policy
ON public.assembly_votes;


-- SELECT

CREATE POLICY
assembly_votes_select_policy
ON public.assembly_votes
FOR SELECT
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        assembly_votes.cep
    )

    AND (

        LOWER(
            COALESCE(
                assembly_votes.user_email,
                ''
            )
        )
        =
        public.condomit_auth_email()

        OR

        EXISTS (

            SELECT 1

            FROM public.assembly_polls ap

            WHERE

                ap.id =
                    assembly_votes.poll_id

                AND (

                    ap.show_results_immediately
                    = TRUE

                    OR

                    ap.status =
                    'encerrada'

                    OR

                    LOWER(
                        COALESCE(
                            ap.created_by,
                            ''
                        )
                    )
                    =
                    public.condomit_auth_email()

                )

        )

    )

);


-- INSERT

CREATE POLICY
assembly_votes_insert_policy
ON public.assembly_votes
FOR INSERT
TO authenticated
WITH CHECK (

    LOWER(
        COALESCE(
            assembly_votes.user_email,
            ''
        )
    )
    =
    public.condomit_auth_email()

    AND

    public.condomit_user_belongs_to_cep(
        assembly_votes.cep
    )

    AND

    EXISTS (

        SELECT 1

        FROM public.assembly_polls ap

        WHERE

            ap.id =
                assembly_votes.poll_id

            AND

            ap.assembly_id =
                assembly_votes.assembly_id

            AND

            public.condomit_same_cep(
                ap.cep,
                assembly_votes.cep
            )

            AND

            ap.status =
                'aberta'

            AND (
                ap.start_at IS NULL
                OR
                ap.start_at <= NOW()
            )

            AND (
                ap.end_at IS NULL
                OR
                ap.end_at > NOW()
            )

    )

);



-- ============================================================
-- 4. VISITANTES
-- ============================================================

ALTER TABLE IF EXISTS
public.visitors
ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS
visitors_select_policy
ON public.visitors;


DROP POLICY IF EXISTS
visitors_insert_policy
ON public.visitors;


DROP POLICY IF EXISTS
visitors_update_policy
ON public.visitors;


DROP POLICY IF EXISTS
visitors_delete_policy
ON public.visitors;


-- ------------------------------------------------------------
-- SELECT
-- ------------------------------------------------------------

CREATE POLICY
visitors_select_policy
ON public.visitors
FOR SELECT
TO authenticated
USING (

    (
        visitors.cep IS NOT NULL

        AND

        public.condomit_user_belongs_to_cep(
            visitors.cep
        )
    )

    OR

    REGEXP_REPLACE(
        COALESCE(
            visitors.responsible_cpf,
            ''
        ),
        '\D',
        '',
        'g'
    )
    =
    public.condomit_current_user_cpf()

);


-- ------------------------------------------------------------
-- INSERT
--
-- O novo JavaScript sempre envia CEP.
-- Portanto não permitimos novos registros
-- sem identificação do condomínio.
-- ------------------------------------------------------------

CREATE POLICY
visitors_insert_policy
ON public.visitors
FOR INSERT
TO authenticated
WITH CHECK (

    public.condomit_auth_email() <> ''

    AND

    public.condomit_current_user_type()
    IN (
        'sindico',
        'síndico',
        'porteiro',
        'morador'
    )

    AND

    visitors.cep IS NOT NULL

    AND

    public.condomit_user_belongs_to_cep(
        visitors.cep
    )

);


-- ------------------------------------------------------------
-- UPDATE
-- ------------------------------------------------------------

CREATE POLICY
visitors_update_policy
ON public.visitors
FOR UPDATE
TO authenticated
USING (

    (
        visitors.cep IS NOT NULL

        AND

        public.condomit_user_belongs_to_cep(
            visitors.cep
        )
    )

    OR

    REGEXP_REPLACE(
        COALESCE(
            visitors.responsible_cpf,
            ''
        ),
        '\D',
        '',
        'g'
    )
    =
    public.condomit_current_user_cpf()

)
WITH CHECK (

    visitors.cep IS NOT NULL

    AND

    public.condomit_user_belongs_to_cep(
        visitors.cep
    )

);


-- ------------------------------------------------------------
-- DELETE
-- ------------------------------------------------------------

CREATE POLICY
visitors_delete_policy
ON public.visitors
FOR DELETE
TO authenticated
USING (

    public.condomit_current_user_type()
    IN (
        'sindico',
        'síndico',
        'porteiro'
    )

    AND

    visitors.cep IS NOT NULL

    AND

    public.condomit_user_belongs_to_cep(
        visitors.cep
    )

);



-- ============================================================
-- 5. MARKETPLACE
-- ============================================================

ALTER TABLE
public.marketplace_items
ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS
marketplace_items_select_policy
ON public.marketplace_items;


DROP POLICY IF EXISTS
marketplace_items_insert_policy
ON public.marketplace_items;


DROP POLICY IF EXISTS
marketplace_items_update_policy
ON public.marketplace_items;


DROP POLICY IF EXISTS
marketplace_items_delete_policy
ON public.marketplace_items;


-- ------------------------------------------------------------
-- SELECT
-- Usuários só veem anúncios do próprio condomínio
-- ------------------------------------------------------------

CREATE POLICY
marketplace_items_select_policy
ON public.marketplace_items
FOR SELECT
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        marketplace_items.cep
    )

);


-- ------------------------------------------------------------
-- INSERT
-- ------------------------------------------------------------

CREATE POLICY
marketplace_items_insert_policy
ON public.marketplace_items
FOR INSERT
TO authenticated
WITH CHECK (

    public.condomit_auth_email() <> ''

    AND

    public.condomit_user_belongs_to_cep(
        marketplace_items.cep
    )

);


-- ------------------------------------------------------------
-- UPDATE
--
-- Observação:
-- sua tabela atual não possui user_email.
-- Portanto não é possível identificar com segurança
-- o autor original usando apenas user_name.
--
-- Esta policy mantém compatibilidade com a estrutura
-- que você forneceu.
-- ------------------------------------------------------------

CREATE POLICY
marketplace_items_update_policy
ON public.marketplace_items
FOR UPDATE
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        marketplace_items.cep
    )

)
WITH CHECK (

    public.condomit_user_belongs_to_cep(
        marketplace_items.cep
    )

);


-- ------------------------------------------------------------
-- DELETE
-- ------------------------------------------------------------

CREATE POLICY
marketplace_items_delete_policy
ON public.marketplace_items
FOR DELETE
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        marketplace_items.cep
    )

);



-- ============================================================
-- 6. ACHADOS E PERDIDOS
-- ============================================================

ALTER TABLE
public.lost_and_found_items
ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS
lost_and_found_items_select_policy
ON public.lost_and_found_items;


DROP POLICY IF EXISTS
lost_and_found_items_insert_policy
ON public.lost_and_found_items;


DROP POLICY IF EXISTS
lost_and_found_items_update_policy
ON public.lost_and_found_items;


DROP POLICY IF EXISTS
lost_and_found_items_delete_policy
ON public.lost_and_found_items;


-- ------------------------------------------------------------
-- SELECT
-- ------------------------------------------------------------

CREATE POLICY
lost_and_found_items_select_policy
ON public.lost_and_found_items
FOR SELECT
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        lost_and_found_items.cep
    )

);


-- ------------------------------------------------------------
-- INSERT
-- ------------------------------------------------------------

CREATE POLICY
lost_and_found_items_insert_policy
ON public.lost_and_found_items
FOR INSERT
TO authenticated
WITH CHECK (

    public.condomit_auth_email() <> ''

    AND

    public.condomit_user_belongs_to_cep(
        lost_and_found_items.cep
    )

);


-- ------------------------------------------------------------
-- UPDATE
-- ------------------------------------------------------------

CREATE POLICY
lost_and_found_items_update_policy
ON public.lost_and_found_items
FOR UPDATE
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        lost_and_found_items.cep
    )

)
WITH CHECK (

    public.condomit_user_belongs_to_cep(
        lost_and_found_items.cep
    )

);


-- ------------------------------------------------------------
-- DELETE
-- ------------------------------------------------------------

CREATE POLICY
lost_and_found_items_delete_policy
ON public.lost_and_found_items
FOR DELETE
TO authenticated
USING (

    public.condomit_user_belongs_to_cep(
        lost_and_found_items.cep
    )

);



-- ============================================================
-- 7. PRIVILÉGIOS POSTGREST
-- ============================================================

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.marketplace_items
TO authenticated;


GRANT SELECT, INSERT, UPDATE, DELETE
ON public.lost_and_found_items
TO authenticated;


GRANT SELECT, INSERT, UPDATE, DELETE
ON public.visitors
TO authenticated;


GRANT SELECT, INSERT, UPDATE, DELETE
ON public.assembly_chat_messages
TO authenticated;


GRANT SELECT, INSERT, UPDATE, DELETE
ON public.assembly_polls
TO authenticated;


GRANT SELECT, INSERT, UPDATE, DELETE
ON public.assembly_poll_options
TO authenticated;


GRANT SELECT, INSERT, UPDATE, DELETE
ON public.assembly_votes
TO authenticated;



-- ============================================================
-- 8. ATUALIZAR CACHE DO POSTGREST
-- ============================================================

NOTIFY pgrst, 'reload schema';