-- ============================================================
-- MIGRAÇÃO 018 - MURAL DE AVISOS, NOTIFICAÇÕES E TRANSFERÊNCIA
-- Condomit
-- Requer as migrations anteriores (principalmente 012, 015, 016 e 017).
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. MURAL DE AVISOS PERMANENTE E SEPARADO DAS NOTIFICAÇÕES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.condominium_notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE RESTRICT,
  category TEXT NOT NULL DEFAULT 'Avisos'
    CHECK (category IN ('Avisos', 'Reservas', 'Assembleias', 'Entregas')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  details TEXT,
  created_by TEXT,
  created_by_name TEXT,
  source TEXT NOT NULL DEFAULT 'manual',
  legacy_notification_id BIGINT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT condominium_notices_title_check CHECK (CHAR_LENGTH(TRIM(title)) BETWEEN 1 AND 160),
  CONSTRAINT condominium_notices_description_check CHECK (CHAR_LENGTH(TRIM(description)) BETWEEN 1 AND 4000)
);

CREATE INDEX IF NOT EXISTS idx_condominium_notices_cep_created_at
  ON public.condominium_notices (cep, created_at DESC, id DESC);

ALTER TABLE public.condominium_notices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS condominium_notices_select_same_condo ON public.condominium_notices;
CREATE POLICY condominium_notices_select_same_condo
ON public.condominium_notices
FOR SELECT TO authenticated
USING (
  public.condomit_auth_email() <> ''
  AND public.condomit_same_cep(cep, public.condomit_current_user_cep())
);

-- O histórico do mural é permanente para usuários do aplicativo.
-- Publicação ocorre exclusivamente pela RPC SECURITY DEFINER abaixo.
DROP POLICY IF EXISTS condominium_notices_insert_direct ON public.condominium_notices;
DROP POLICY IF EXISTS condominium_notices_update_direct ON public.condominium_notices;
DROP POLICY IF EXISTS condominium_notices_delete_direct ON public.condominium_notices;
REVOKE INSERT, UPDATE, DELETE ON public.condominium_notices FROM authenticated;
GRANT SELECT ON public.condominium_notices TO authenticated;

-- ------------------------------------------------------------
-- 2. NOTIFICAÇÕES PASSAM A REGISTRAR EVENTOS DO MURAL
-- ------------------------------------------------------------
ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS event_type TEXT,
  ADD COLUMN IF NOT EXISTS related_notice_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_notifications_event_notice
  ON public.notifications (related_notice_id)
  WHERE event_type = 'mural_notice_created';

CREATE OR REPLACE FUNCTION public.condomit_notify_mural_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF COALESCE(NEW.source, '') <> 'legacy' AND NOT EXISTS (
    SELECT 1
    FROM public.notifications n
    WHERE n.event_type = 'mural_notice_created'
      AND n.related_notice_id = NEW.id
  ) THEN
    INSERT INTO public.notifications (
      cep,
      category,
      title,
      description,
      created_by,
      created_by_name,
      event_type,
      related_notice_id,
      created_at
    ) VALUES (
      NEW.cep,
      'Avisos',
      'Mural de Avisos atualizado',
      'Novo aviso publicado: ' || NEW.title,
      NEW.created_by,
      COALESCE(NULLIF(NEW.created_by_name, ''), 'Condomit'),
      'mural_notice_created',
      NEW.id,
      NEW.created_at
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_condomit_notify_mural_change ON public.condominium_notices;
CREATE TRIGGER trg_condomit_notify_mural_change
AFTER INSERT ON public.condominium_notices
FOR EACH ROW
EXECUTE FUNCTION public.condomit_notify_mural_change();

-- ------------------------------------------------------------
-- 3. MIGRA AVISOS ANTIGOS PARA O NOVO MURAL SEM APAGAR HISTÓRICO
-- ------------------------------------------------------------
INSERT INTO public.condominium_notices (
  cep,
  category,
  title,
  description,
  details,
  created_by,
  created_by_name,
  source,
  legacy_notification_id,
  created_at
)
SELECT
  n.cep,
  COALESCE(NULLIF(n.category, ''), 'Avisos'),
  n.title,
  n.description,
  n.description,
  n.created_by,
  n.created_by_name,
  'legacy',
  n.id,
  n.created_at
FROM public.notifications n
WHERE n.category = 'Avisos'
  AND COALESCE(n.event_type, '') <> 'mural_notice_created'
  AND NOT EXISTS (
    SELECT 1
    FROM public.condominium_notices cn
    WHERE cn.legacy_notification_id = n.id
  );

-- ------------------------------------------------------------
-- 4. RPCS DO MURAL
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.condomit_create_wall_notice(
  target_category TEXT,
  target_title TEXT,
  target_description TEXT,
  target_details TEXT DEFAULT NULL,
  target_source TEXT DEFAULT 'manual'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  caller_email TEXT := public.condomit_auth_email();
  caller_role TEXT := public.condomit_current_user_role();
  caller_cep TEXT := public.condomit_current_user_cep();
  caller_name TEXT;
  normalized_category TEXT := TRIM(COALESCE(target_category, 'Avisos'));
  saved_row public.condominium_notices%ROWTYPE;
BEGIN
  IF caller_email = '' OR caller_cep IS NULL THEN
    RAISE EXCEPTION 'Sessão ou condomínio inválido.' USING ERRCODE = '42501';
  END IF;

  IF caller_role NOT IN ('sindico', 'síndico', 'admin') THEN
    RAISE EXCEPTION 'Apenas o síndico pode publicar no Mural de Avisos.' USING ERRCODE = '42501';
  END IF;

  IF normalized_category NOT IN ('Avisos', 'Reservas', 'Assembleias', 'Entregas') THEN
    RAISE EXCEPTION 'Categoria de aviso inválida.' USING ERRCODE = '22023';
  END IF;

  IF NULLIF(TRIM(COALESCE(target_title, '')), '') IS NULL
     OR NULLIF(TRIM(COALESCE(target_description, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Título e descrição são obrigatórios.' USING ERRCODE = '23502';
  END IF;

  SELECT COALESCE(NULLIF(TRIM(u.name), ''), u.email)
  INTO caller_name
  FROM public.users u
  WHERE LOWER(COALESCE(u.email, '')) = caller_email
  LIMIT 1;

  INSERT INTO public.condominium_notices (
    cep,
    category,
    title,
    description,
    details,
    created_by,
    created_by_name,
    source
  ) VALUES (
    caller_cep,
    normalized_category,
    TRIM(target_title),
    TRIM(target_description),
    COALESCE(NULLIF(TRIM(COALESCE(target_details, '')), ''), TRIM(target_description)),
    caller_email,
    COALESCE(caller_name, caller_email),
    COALESCE(NULLIF(TRIM(COALESCE(target_source, '')), ''), 'manual')
  )
  RETURNING * INTO saved_row;

  RETURN to_jsonb(saved_row);
END;
$$;

CREATE OR REPLACE FUNCTION public.condomit_list_wall_notices()
RETURNS SETOF JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT to_jsonb(cn)
  FROM public.condominium_notices cn
  WHERE public.condomit_auth_email() <> ''
    AND public.condomit_same_cep(cn.cep, public.condomit_current_user_cep())
  ORDER BY cn.created_at DESC, cn.id DESC;
$$;

-- ------------------------------------------------------------
-- 5. MORADORES: INCLUI O EX-SÍNDICO APÓS TRANSFERÊNCIA DE CARGO
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.condomit_list_condo_residents()
RETURNS TABLE (
  email TEXT,
  name TEXT,
  phone TEXT,
  user_type TEXT,
  profile_photo TEXT,
  apartment TEXT,
  block TEXT,
  cep TEXT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  current_cep TEXT := public.condomit_current_user_cep();
BEGIN
  IF public.condomit_auth_email() = '' THEN
    RAISE EXCEPTION 'Sessão inválida.' USING ERRCODE = '42501';
  END IF;

  IF current_cep IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    u.email::TEXT,
    COALESCE(NULLIF(u.name, ''), u.email)::TEXT,
    COALESCE(u.phone, '')::TEXT,
    u.user_type::TEXT,
    u.profile_photo::TEXT,
    COALESCE(NULLIF(link.apartment, ''), NULLIF(u.condominium ->> 'apartment', ''), '')::TEXT,
    COALESCE(NULLIF(link.block, ''), NULLIF(u.condominium ->> 'block', ''), '')::TEXT,
    current_cep::TEXT
  FROM public.users u
  LEFT JOIN LATERAL (
    SELECT
      uc.apartment::TEXT AS apartment,
      uc.block::TEXT AS block,
      TRUE AS has_link
    FROM public.user_condominiums uc
    WHERE LOWER(COALESCE(uc.user_email, '')) = LOWER(COALESCE(u.email, ''))
      AND public.condomit_same_cep(uc.condominium_id::TEXT, current_cep)
    LIMIT 1
  ) link ON TRUE
  WHERE LOWER(COALESCE(u.user_type, '')) = 'morador'
    AND (
      COALESCE(link.has_link, FALSE)
      OR public.condomit_same_cep(
        COALESCE(
          NULLIF(u.condominium ->> 'cep', ''),
          NULLIF(u.condominium ->> 'condominium_id', ''),
          NULLIF(u.condominium ->> 'condominium_cep', ''),
          NULLIF(u.condominium ->> 'condominiumId', '')
        ),
        current_cep
      )
    )
  ORDER BY LOWER(COALESCE(u.name, u.email)), LOWER(u.email);
END;
$$;

-- ------------------------------------------------------------
-- 6. TRANSFERÊNCIA DE SÍNDICO + AVISO AUTOMÁTICO NO MURAL
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.condomit_promote_resident_to_sindico(target_email TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  caller_email TEXT := public.condomit_auth_email();
  caller_role TEXT := public.condomit_current_user_role();
  caller_cep TEXT := public.condomit_current_user_cep();
  caller_name TEXT;
  resident_email TEXT;
  resident_name TEXT;
  saved_notice public.condominium_notices%ROWTYPE;
BEGIN
  IF caller_email = '' OR caller_cep IS NULL OR caller_role NOT IN ('sindico', 'síndico') THEN
    RAISE EXCEPTION 'Apenas o síndico atual pode transferir a função.' USING ERRCODE = '42501';
  END IF;

  SELECT
    u.email,
    COALESCE(NULLIF(TRIM(u.name), ''), u.email)
  INTO
    resident_email,
    resident_name
  FROM public.users u
  JOIN public.user_condominiums uc
    ON LOWER(COALESCE(uc.user_email, '')) = LOWER(COALESCE(u.email, ''))
  WHERE LOWER(COALESCE(u.email, '')) = LOWER(TRIM(COALESCE(target_email, '')))
    AND LOWER(COALESCE(u.user_type, '')) = 'morador'
    AND public.condomit_same_cep(uc.condominium_id::TEXT, caller_cep)
  LIMIT 1;

  IF resident_email IS NULL THEN
    RAISE EXCEPTION 'Morador não encontrado neste condomínio.' USING ERRCODE = 'P0002';
  END IF;

  IF LOWER(resident_email) = caller_email THEN
    RAISE EXCEPTION 'Não é possível promover a própria conta.' USING ERRCODE = '22023';
  END IF;

  SELECT COALESCE(NULLIF(TRIM(u.name), ''), u.email)
  INTO caller_name
  FROM public.users u
  WHERE LOWER(COALESCE(u.email, '')) = caller_email
  LIMIT 1;

  UPDATE public.users
  SET user_type = 'morador'
  WHERE LOWER(COALESCE(email, '')) = caller_email;

  UPDATE public.users
  SET user_type = 'sindico'
  WHERE LOWER(COALESCE(email, '')) = LOWER(resident_email);

  -- O vínculo condominial do antigo síndico não é removido.
  -- Mesmo em cadastros antigos sem user_condominiums, a listagem de moradores
  -- usa também users.condominium, garantindo que ele passe a ser contabilizado.

  INSERT INTO public.condominium_notices (
    cep,
    category,
    title,
    description,
    details,
    created_by,
    created_by_name,
    source
  ) VALUES (
    caller_cep,
    'Avisos',
    'Novo síndico do condomínio',
    'A função de síndico foi transferida de ' || COALESCE(caller_name, caller_email) || ' para ' || COALESCE(resident_name, resident_email) || '.',
    'O condomínio possui um novo síndico responsável. ' || COALESCE(resident_name, resident_email) || ' assumiu a função de síndico, enquanto ' || COALESCE(caller_name, caller_email) || ' passou a utilizar a Condomit como morador.',
    caller_email,
    COALESCE(caller_name, caller_email),
    'role_transfer'
  )
  RETURNING * INTO saved_notice;

  RETURN jsonb_build_object(
    'changed', TRUE,
    'old_sindico_email', caller_email,
    'old_sindico_name', caller_name,
    'new_sindico_email', resident_email,
    'new_sindico_name', resident_name,
    'cep', caller_cep,
    'notice_id', saved_notice.id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.condomit_create_wall_notice(TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_list_wall_notices() TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_list_condo_residents() TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_promote_resident_to_sindico(TEXT) TO authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;
