-- ============================================================
-- CONDOMIT - MIGRAÇÃO 021
-- Livro digital de ocorrências para Síndico, Morador e Porteiro
-- Requer as migrations anteriores, especialmente a 020.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. TABELA DE OCORRÊNCIAS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.occurrences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  reporter_email TEXT NOT NULL REFERENCES public.users(email) ON UPDATE CASCADE ON DELETE RESTRICT,
  reporter_name TEXT NOT NULL,
  reporter_role TEXT NOT NULL CHECK (reporter_role IN ('morador', 'porteiro', 'sindico')),
  occurrence_date DATE NOT NULL,
  occurrence_time TIME NOT NULL,
  unit_involved TEXT,
  occurrence_author TEXT,
  description TEXT NOT NULL,
  signature_data TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT occurrences_description_not_blank CHECK (LENGTH(TRIM(description)) > 0),
  CONSTRAINT occurrences_signature_png CHECK (signature_data LIKE 'data:image/png;base64,%'),
  CONSTRAINT occurrences_signature_size CHECK (OCTET_LENGTH(signature_data) <= 1500000)
);

CREATE INDEX IF NOT EXISTS idx_occurrences_cep_created_at
  ON public.occurrences (cep, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_occurrences_reporter_email
  ON public.occurrences (LOWER(reporter_email), created_at DESC);

CREATE INDEX IF NOT EXISTS idx_occurrences_occurrence_date
  ON public.occurrences (cep, occurrence_date DESC);

-- ------------------------------------------------------------
-- 2. IDENTIDADE CONFIÁVEL DO RESPONSÁVEL PELO REGISTRO
-- O front-end mostra nome e função automaticamente, mas o banco
-- também substitui esses valores pelos dados reais da conta.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.condomit_prepare_occurrence()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  caller_email TEXT := public.condomit_auth_email();
  caller_user public.users%ROWTYPE;
  caller_cep TEXT := public.condomit_current_user_cep();
  normalized_role TEXT;
BEGIN
  IF caller_email = '' THEN
    RAISE EXCEPTION 'Usuário não autenticado.' USING ERRCODE = '42501';
  END IF;

  SELECT u.*
  INTO caller_user
  FROM public.users u
  WHERE LOWER(COALESCE(u.email, '')) = caller_email
  LIMIT 1;

  IF caller_user.email IS NULL THEN
    RAISE EXCEPTION 'Usuário autenticado não encontrado em public.users.' USING ERRCODE = '42501';
  END IF;

  IF caller_cep IS NULL OR TRIM(caller_cep) = '' THEN
    RAISE EXCEPTION 'Condomínio do usuário não identificado.' USING ERRCODE = '42501';
  END IF;

  normalized_role := LOWER(TRIM(COALESCE(caller_user.user_type, 'morador')));
  IF normalized_role IN ('síndico', 'sindico') OR normalized_role LIKE 'sind%' THEN
    normalized_role := 'sindico';
  ELSIF normalized_role LIKE 'porteir%' THEN
    normalized_role := 'porteiro';
  ELSE
    normalized_role := 'morador';
  END IF;

  NEW.cep := caller_cep;
  NEW.reporter_email := caller_user.email;
  NEW.reporter_name := COALESCE(NULLIF(TRIM(caller_user.name), ''), 'Usuário');
  NEW.reporter_role := normalized_role;
  NEW.created_at := COALESCE(NEW.created_at, NOW());
  NEW.unit_involved := NULLIF(TRIM(COALESCE(NEW.unit_involved, '')), '');
  NEW.occurrence_author := NULLIF(TRIM(COALESCE(NEW.occurrence_author, '')), '');
  NEW.description := TRIM(COALESCE(NEW.description, ''));

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_condomit_prepare_occurrence ON public.occurrences;
CREATE TRIGGER trg_condomit_prepare_occurrence
BEFORE INSERT ON public.occurrences
FOR EACH ROW
EXECUTE FUNCTION public.condomit_prepare_occurrence();

-- ------------------------------------------------------------
-- 3. RLS
-- Morador/Porteiro: veem apenas ocorrências registradas por eles.
-- Síndico: vê todas as ocorrências do próprio condomínio.
-- Todos os três perfis podem registrar uma ocorrência em sua conta.
-- ------------------------------------------------------------
ALTER TABLE public.occurrences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS occurrences_select_policy ON public.occurrences;
DROP POLICY IF EXISTS occurrences_insert_policy ON public.occurrences;

CREATE POLICY occurrences_select_policy
ON public.occurrences
FOR SELECT
TO authenticated
USING (
  public.condomit_user_belongs_to_cep(occurrences.cep)
  AND (
    LOWER(COALESCE(occurrences.reporter_email, '')) = public.condomit_auth_email()
    OR public.condomit_current_user_role() IN ('sindico', 'síndico', 'admin')
    OR public.condomit_current_user_type() IN ('sindico', 'síndico', 'admin')
  )
);

CREATE POLICY occurrences_insert_policy
ON public.occurrences
FOR INSERT
TO authenticated
WITH CHECK (
  public.condomit_user_belongs_to_cep(occurrences.cep)
  AND LOWER(COALESCE(occurrences.reporter_email, '')) = public.condomit_auth_email()
  AND occurrences.reporter_role IN ('morador', 'porteiro', 'sindico')
);

REVOKE ALL ON public.occurrences FROM anon;
GRANT SELECT, INSERT ON public.occurrences TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.occurrences_id_seq TO authenticated;

REVOKE ALL ON FUNCTION public.condomit_prepare_occurrence() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.condomit_prepare_occurrence() TO authenticated;

COMMIT;
