-- ============================================================
-- CONDOMIT - MIGRAÇÃO 024
-- Suite avançada de gestão: documentos, financeiro, consumo,
-- patrimônio, SLA, estacionamento, carregadores, emergência,
-- calendário, tarefas, auditoria, permissões, administradoras,
-- satisfação, gamificação e melhorias de marketplace/achados.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 0. HELPERS DE ACESSO
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.condomit_is_management_role()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT public.condomit_current_user_type() IN (
    'sindico', 'síndico', 'admin', 'administradora', 'administrador'
  );
$$;

CREATE TABLE IF NOT EXISTS public.management_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cnpj TEXT,
  email TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.management_company_users (
  company_id BIGINT NOT NULL REFERENCES public.management_companies(id) ON DELETE CASCADE,
  user_email TEXT NOT NULL REFERENCES public.users(email) ON UPDATE CASCADE ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'administradora',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (company_id, user_email)
);

CREATE TABLE IF NOT EXISTS public.managed_condominiums (
  company_id BIGINT NOT NULL REFERENCES public.management_companies(id) ON DELETE CASCADE,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (company_id, cep)
);

CREATE OR REPLACE FUNCTION public.condomit_admin_manages_cep(target_cep TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.management_company_users mcu
    JOIN public.managed_condominiums mc ON mc.company_id = mcu.company_id
    WHERE LOWER(mcu.user_email) = public.condomit_auth_email()
      AND mc.active = TRUE
      AND public.condomit_same_cep(mc.cep, target_cep)
  );
$$;

CREATE OR REPLACE FUNCTION public.condomit_can_access_cep(target_cep TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT public.condomit_user_belongs_to_cep(target_cep)
      OR public.condomit_admin_manages_cep(target_cep);
$$;

CREATE OR REPLACE FUNCTION public.condomit_can_manage_cep(target_cep TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT public.condomit_is_management_role()
     AND public.condomit_can_access_cep(target_cep);
$$;


-- Dashboard seguro para administradoras. A função SECURITY DEFINER permite
-- consolidar dados de condomínios vinculados sem enfraquecer as RLS antigas.
CREATE OR REPLACE FUNCTION public.condomit_managed_condominiums_dashboard()
RETURNS TABLE (
  company_id BIGINT,
  company_name TEXT,
  cep TEXT,
  condominium_name TEXT,
  open_tickets BIGINT,
  pending_maintenance BIGINT,
  active_emergencies BIGINT,
  documents_count BIGINT,
  current_balance NUMERIC
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    mc.company_id,
    cmp.name AS company_name,
    mc.cep,
    COALESCE(c.condominium_name, 'Condomínio ' || mc.cep) AS condominium_name,
    (SELECT COUNT(*) FROM public.service_tickets st
      WHERE public.condomit_same_cep(st.cep, mc.cep)
        AND st.status NOT IN ('resolvido','cancelado')) AS open_tickets,
    (SELECT COUNT(*) FROM public.maintenance_items mi
      WHERE public.condomit_same_cep(mi.cep, mc.cep)
        AND COALESCE(mi.status,'') <> 'concluida') AS pending_maintenance,
    (SELECT COUNT(*) FROM public.emergency_alerts ea
      WHERE public.condomit_same_cep(ea.cep, mc.cep)
        AND ea.active = TRUE) AS active_emergencies,
    (SELECT COUNT(*) FROM public.condominium_documents cd
      WHERE public.condomit_same_cep(cd.cep, mc.cep)) AS documents_count,
    COALESCE((SELECT SUM(CASE WHEN fe.entry_type='receita' THEN fe.amount ELSE -fe.amount END)
      FROM public.financial_entries fe
      WHERE public.condomit_same_cep(fe.cep, mc.cep)
        AND fe.status <> 'cancelado'),0) AS current_balance
  FROM public.management_company_users mcu
  JOIN public.management_companies cmp ON cmp.id = mcu.company_id
  JOIN public.managed_condominiums mc ON mc.company_id = mcu.company_id AND mc.active = TRUE
  LEFT JOIN public.condominiums c ON public.condomit_same_cep(c.cep, mc.cep)
  WHERE LOWER(mcu.user_email) = public.condomit_auth_email()
  ORDER BY cmp.name, COALESCE(c.condominium_name, mc.cep);
$$;

-- ------------------------------------------------------------
-- 1. CENTRAL DE DOCUMENTOS + BASE DE CONHECIMENTO DA IA
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.condominium_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Geral',
  description TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  file_url TEXT,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  visibility TEXT NOT NULL DEFAULT 'todos' CHECK (visibility IN ('todos','gestao','moradores','portaria')),
  expires_at DATE,
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_condominium_documents_cep ON public.condominium_documents(cep, category, updated_at DESC);

-- ------------------------------------------------------------
-- 2. FINANCEIRO E CONSUMO
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.financial_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('receita','despesa')),
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  due_date DATE,
  paid_date DATE,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','pago','atrasado','cancelado')),
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_financial_entries_cep_date ON public.financial_entries(cep, due_date DESC);

CREATE TABLE IF NOT EXISTS public.budget_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  budget_month DATE NOT NULL,
  category TEXT NOT NULL DEFAULT 'Geral',
  planned_amount NUMERIC(12,2) NOT NULL CHECK (planned_amount >= 0),
  notes TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(cep, budget_month, category)
);
CREATE INDEX IF NOT EXISTS idx_budget_plans_cep_month ON public.budget_plans(cep, budget_month DESC);


CREATE TABLE IF NOT EXISTS public.utility_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  unit TEXT NOT NULL,
  block TEXT,
  utility_type TEXT NOT NULL CHECK (utility_type IN ('agua','gas','energia')),
  reading_value NUMERIC(14,3) NOT NULL CHECK (reading_value >= 0),
  measured_at DATE NOT NULL DEFAULT CURRENT_DATE,
  notes TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_utility_readings_cep_unit ON public.utility_readings(cep, unit, utility_type, measured_at DESC);

-- ------------------------------------------------------------
-- 3. PATRIMÔNIO + QR + MANUTENÇÃO RECORRENTE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.condominium_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  name TEXT NOT NULL,
  asset_type TEXT NOT NULL,
  location TEXT NOT NULL,
  serial_number TEXT,
  supplier TEXT,
  warranty_until DATE,
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','manutencao','inativo','baixado')),
  qr_code TEXT UNIQUE,
  notes TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_assets_cep ON public.condominium_assets(cep, status, asset_type);

CREATE TABLE IF NOT EXISTS public.maintenance_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  asset_id BIGINT REFERENCES public.condominium_assets(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  location TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  interval_days INTEGER NOT NULL DEFAULT 30 CHECK (interval_days > 0),
  next_due DATE NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.maintenance_items ADD COLUMN IF NOT EXISTS asset_id BIGINT REFERENCES public.condominium_assets(id) ON DELETE SET NULL;
ALTER TABLE public.maintenance_items ADD COLUMN IF NOT EXISTS template_id BIGINT REFERENCES public.maintenance_templates(id) ON DELETE SET NULL;

CREATE OR REPLACE FUNCTION public.condomit_generate_due_maintenance()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  item RECORD;
  inserted_count INTEGER := 0;
BEGIN
  FOR item IN
    SELECT * FROM public.maintenance_templates mt
    WHERE mt.active = TRUE
      AND mt.next_due <= CURRENT_DATE
      AND public.condomit_can_manage_cep(mt.cep)
  LOOP
    INSERT INTO public.maintenance_items(
      cep, title, description, location, category, frequency, next_date,
      status, created_by, asset_id, template_id
    ) VALUES (
      item.cep, item.title, item.description, item.location, item.category,
      item.interval_days::TEXT || ' dias', item.next_due, 'pendente',
      public.condomit_auth_email(), item.asset_id, item.id
    );

    UPDATE public.maintenance_templates
       SET next_due = item.next_due + item.interval_days,
           updated_at = NOW()
     WHERE id = item.id;
    inserted_count := inserted_count + 1;
  END LOOP;
  RETURN inserted_count;
END;
$$;

-- ------------------------------------------------------------
-- 4. CHAMADOS COM SLA
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.service_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Geral',
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('baixa','normal','alta','critica')),
  status TEXT NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto','em_analise','em_andamento','aguardando_prestador','resolvido','cancelado')),
  requester_email TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  assigned_to TEXT,
  sla_due_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_service_tickets_cep_status ON public.service_tickets(cep, status, sla_due_at);

-- ------------------------------------------------------------
-- 5. ESTACIONAMENTO + CARREGADORES ELÉTRICOS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.parking_spaces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  code TEXT NOT NULL,
  unit TEXT,
  block TEXT,
  space_type TEXT NOT NULL DEFAULT 'morador' CHECK (space_type IN ('morador','visitante','pcd','moto','eletrico')),
  status TEXT NOT NULL DEFAULT 'livre' CHECK (status IN ('livre','ocupada','emprestada','bloqueada')),
  vehicle_plate TEXT,
  user_email TEXT,
  borrowed_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (cep, code)
);

CREATE TABLE IF NOT EXISTS public.ev_chargers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  power_kw NUMERIC(8,2),
  status TEXT NOT NULL DEFAULT 'disponivel' CHECK (status IN ('disponivel','ocupado','manutencao','inativo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ev_charger_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  charger_id BIGINT NOT NULL REFERENCES public.ev_chargers(id) ON DELETE CASCADE,
  user_email TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ NOT NULL,
  kwh NUMERIC(10,3),
  status TEXT NOT NULL DEFAULT 'reservado' CHECK (status IN ('reservado','em_uso','concluido','cancelado')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (end_at > start_at)
);
CREATE INDEX IF NOT EXISTS idx_ev_bookings_charger_time ON public.ev_charger_bookings(charger_id, start_at, end_at);

-- ------------------------------------------------------------
-- 6. EMERGÊNCIA + CONFIRMAÇÃO DE LEITURA
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.emergency_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'alta' CHECK (severity IN ('moderada','alta','critica')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.communication_reads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  user_email TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  acknowledged BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE(resource_type, resource_id, user_email)
);

-- ------------------------------------------------------------
-- 7. CALENDÁRIO GERAL + TAREFAS DE ASSEMBLEIA
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.condominium_calendar_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  event_type TEXT NOT NULL DEFAULT 'geral',
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ,
  source_type TEXT,
  source_id TEXT,
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.assembly_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  assembly_id BIGINT,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  assigned_to TEXT,
  due_date DATE,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','em_andamento','concluida','cancelada')),
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 8. AUDITORIA + PERMISSÕES GRANULARES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  actor_email TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  details JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_log_cep_time ON public.audit_log(cep, created_at DESC);

CREATE TABLE IF NOT EXISTS public.role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  role TEXT NOT NULL,
  permission TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (cep, role, permission)
);

CREATE OR REPLACE FUNCTION public.condomit_has_permission(target_cep TEXT, permission_name TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN public.condomit_can_manage_cep(target_cep) THEN TRUE
    ELSE COALESCE((
      SELECT rp.enabled
      FROM public.role_permissions rp
      WHERE public.condomit_same_cep(rp.cep, target_cep)
        AND LOWER(rp.role) = public.condomit_current_user_type()
        AND rp.permission = permission_name
      LIMIT 1
    ), FALSE)
  END;
$$;

-- ------------------------------------------------------------
-- 9. PESQUISA DE SATISFAÇÃO + GAMIFICAÇÃO COMUNITÁRIA
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.satisfaction_surveys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  title TEXT NOT NULL,
  question TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closes_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.satisfaction_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id BIGINT NOT NULL REFERENCES public.satisfaction_surveys(id) ON DELETE CASCADE,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  user_email TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
  comment TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (survey_id, user_email)
);

CREATE TABLE IF NOT EXISTS public.engagement_badges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  user_email TEXT NOT NULL REFERENCES public.users(email) ON UPDATE CASCADE ON DELETE CASCADE,
  badge_code TEXT NOT NULL,
  label TEXT NOT NULL,
  points INTEGER NOT NULL DEFAULT 0 CHECK (points >= 0),
  awarded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (cep, user_email, badge_code)
);

-- ------------------------------------------------------------
-- 10. MELHORIAS MARKETPLACE + ACHADOS E PERDIDOS
-- ------------------------------------------------------------
ALTER TABLE public.marketplace_items ADD COLUMN IF NOT EXISTS item_status TEXT NOT NULL DEFAULT 'disponivel';
ALTER TABLE public.marketplace_items ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '30 days');
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'marketplace_items_item_status_check'
      AND conrelid = 'public.marketplace_items'::regclass
  ) THEN
    ALTER TABLE public.marketplace_items
      ADD CONSTRAINT marketplace_items_item_status_check
      CHECK (item_status IN ('disponivel','reservado','vendido','doado','expirado'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.marketplace_favorites (
  item_id BIGINT NOT NULL REFERENCES public.marketplace_items(id) ON DELETE CASCADE,
  user_email TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY(item_id, user_email)
);

ALTER TABLE public.lost_and_found_items ADD COLUMN IF NOT EXISTS item_status TEXT NOT NULL DEFAULT 'ativo';
ALTER TABLE public.lost_and_found_items ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
ALTER TABLE public.lost_and_found_items ADD COLUMN IF NOT EXISTS created_by TEXT DEFAULT public.condomit_auth_email();

CREATE OR REPLACE FUNCTION public.condomit_expire_marketplace_items()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE changed INTEGER;
BEGIN
  UPDATE public.marketplace_items
     SET item_status = 'expirado'
   WHERE item_status IN ('disponivel','reservado')
     AND expires_at IS NOT NULL
     AND expires_at < NOW()
     AND public.condomit_can_access_cep(cep);
  GET DIAGNOSTICS changed = ROW_COUNT;
  RETURN changed;
END;
$$;

CREATE OR REPLACE FUNCTION public.condomit_archive_old_lost_found()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE changed INTEGER;
BEGIN
  UPDATE public.lost_and_found_items
     SET item_status = 'arquivado', archived_at = NOW()
   WHERE item_status = 'ativo'
     AND item_date < CURRENT_DATE - 90
     AND public.condomit_can_access_cep(cep);
  GET DIAGNOSTICS changed = ROW_COUNT;
  RETURN changed;
END;
$$;

CREATE OR REPLACE FUNCTION public.condomit_suggest_lost_found_matches()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE changed INTEGER := 0; r RECORD; score INTEGER;
BEGIN
  FOR r IN
    SELECT l.id lost_id, f.id found_id, l.cep,
           l.item_name lost_name, f.item_name found_name,
           l.location lost_location, f.location found_location,
           LOWER(COALESCE(l.created_by,'')) lost_creator,
           LOWER(COALESCE(f.created_by,'')) found_creator
    FROM public.lost_and_found_items l
    JOIN public.lost_and_found_items f ON public.condomit_same_cep(l.cep, f.cep) AND l.id <> f.id
    WHERE l.item_type='Perdido' AND f.item_type='Encontrado'
      AND l.item_status='ativo' AND f.item_status='ativo'
      AND public.condomit_can_access_cep(l.cep)
      AND ABS(l.item_date - f.item_date) <= 30
  LOOP
    score := 35;
    IF LOWER(r.lost_name) = LOWER(r.found_name) THEN score := score + 45;
    ELSIF LOWER(r.lost_name) LIKE '%' || LOWER(r.found_name) || '%' OR LOWER(r.found_name) LIKE '%' || LOWER(r.lost_name) || '%' THEN score := score + 30;
    END IF;
    IF LOWER(r.lost_location) = LOWER(r.found_location) THEN score := score + 20; END IF;
    IF score >= 55 THEN
      INSERT INTO public.lost_found_matches(cep,lost_item_id,found_item_id,confidence,status)
      VALUES(r.cep,r.lost_id,r.found_id,LEAST(score,100),'sugerido')
      ON CONFLICT(lost_item_id,found_item_id) DO UPDATE SET confidence=EXCLUDED.confidence;

      IF COALESCE(r.lost_creator,'') <> '' THEN
        INSERT INTO public.notifications(
          cep,category,title,description,recipient_email,event_type,event_key,created_at
        ) VALUES (
          r.cep,'Avisos','Possível item encontrado',
          'Encontramos uma possível correspondência para "' || r.lost_name || '". Abra Achados e Perdidos para conferir.',
          r.lost_creator,'lost_found_match',
          'lost_found_match:' || r.lost_id::TEXT || ':' || r.found_id::TEXT || ':' || r.lost_creator,
          NOW()
        ) ON CONFLICT (event_key) DO NOTHING;
      END IF;

      IF COALESCE(r.found_creator,'') <> '' AND r.found_creator <> r.lost_creator THEN
        INSERT INTO public.notifications(
          cep,category,title,description,recipient_email,event_type,event_key,created_at
        ) VALUES (
          r.cep,'Avisos','Possível correspondência em Achados e Perdidos',
          'O item "' || r.found_name || '" pode corresponder a um item perdido registrado no condomínio.',
          r.found_creator,'lost_found_match',
          'lost_found_match:' || r.lost_id::TEXT || ':' || r.found_id::TEXT || ':' || r.found_creator,
          NOW()
        ) ON CONFLICT (event_key) DO NOTHING;
      END IF;

      changed := changed + 1;
    END IF;
  END LOOP;
  RETURN changed;
END;
$$;

CREATE TABLE IF NOT EXISTS public.lost_found_matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  lost_item_id BIGINT NOT NULL REFERENCES public.lost_and_found_items(id) ON DELETE CASCADE,
  found_item_id BIGINT NOT NULL REFERENCES public.lost_and_found_items(id) ON DELETE CASCADE,
  confidence INTEGER NOT NULL DEFAULT 50 CHECK (confidence BETWEEN 0 AND 100),
  status TEXT NOT NULL DEFAULT 'sugerido' CHECK (status IN ('sugerido','confirmado','descartado')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(lost_item_id, found_item_id)
);


-- ------------------------------------------------------------
-- 10B. FEED, SESSÕES E ENCOMENDAS AVANÇADAS
-- ------------------------------------------------------------
ALTER TABLE public.condominium_notices
  ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS comments_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS attachment_url TEXT;

CREATE TABLE IF NOT EXISTS public.wall_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id BIGINT NOT NULL REFERENCES public.condominium_notices(id) ON DELETE CASCADE,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  user_email TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  user_name TEXT NOT NULL DEFAULT '',
  comment TEXT NOT NULL CHECK (CHAR_LENGTH(TRIM(comment)) BETWEEN 1 AND 1000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wall_reactions (
  notice_id BIGINT NOT NULL REFERENCES public.condominium_notices(id) ON DELETE CASCADE,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  user_email TEXT NOT NULL DEFAULT public.condomit_auth_email(),
  reaction TEXT NOT NULL DEFAULT 'curtir' CHECK (reaction IN ('curtir','apoio','importante')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (notice_id, user_email)
);

CREATE OR REPLACE FUNCTION public.condomit_set_notice_options(
  target_notice_id BIGINT,
  target_pinned BOOLEAN DEFAULT NULL,
  target_comments_enabled BOOLEAN DEFAULT NULL,
  target_attachment_url TEXT DEFAULT NULL
)
RETURNS public.condominium_notices
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE row_data public.condominium_notices%ROWTYPE;
BEGIN
  SELECT * INTO row_data FROM public.condominium_notices WHERE id = target_notice_id;
  IF NOT FOUND OR NOT public.condomit_can_manage_cep(row_data.cep) THEN
    RAISE EXCEPTION 'Sem permissão para alterar este aviso.' USING ERRCODE = '42501';
  END IF;
  UPDATE public.condominium_notices
     SET is_pinned = COALESCE(target_pinned, is_pinned),
         comments_enabled = COALESCE(target_comments_enabled, comments_enabled),
         attachment_url = COALESCE(target_attachment_url, attachment_url)
   WHERE id = target_notice_id
   RETURNING * INTO row_data;
  RETURN row_data;
END;
$$;

CREATE TABLE IF NOT EXISTS public.user_session_log (
  session_id TEXT PRIMARY KEY,
  user_email TEXT NOT NULL REFERENCES public.users(email) ON UPDATE CASCADE ON DELETE CASCADE,
  device_label TEXT NOT NULL DEFAULT 'Navegador',
  user_agent TEXT NOT NULL DEFAULT '',
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_session_log_email ON public.user_session_log(LOWER(user_email), last_seen_at DESC);

ALTER TABLE public.packages
  ADD COLUMN IF NOT EXISTS pickup_code TEXT,
  ADD COLUMN IF NOT EXISTS package_photo_url TEXT,
  ADD COLUMN IF NOT EXISTS overdue_notified_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS idx_packages_pickup_code ON public.packages(pickup_code) WHERE pickup_code IS NOT NULL;

CREATE OR REPLACE FUNCTION public.condomit_packages_set_pickup_code()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NULLIF(TRIM(COALESCE(NEW.pickup_code, '')), '') IS NULL THEN
    NEW.pickup_code := UPPER(SUBSTR(MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT || COALESCE(NEW.recipient_email,'')), 1, 8));
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_packages_set_pickup_code ON public.packages;
CREATE TRIGGER trg_packages_set_pickup_code BEFORE INSERT ON public.packages
FOR EACH ROW EXECUTE FUNCTION public.condomit_packages_set_pickup_code();

UPDATE public.packages
SET pickup_code = UPPER(SUBSTR(MD5(id::TEXT || recipient_email || received_at::TEXT), 1, 8))
WHERE pickup_code IS NULL;

CREATE OR REPLACE FUNCTION public.condomit_notify_old_packages()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE p RECORD; notified INTEGER := 0;
BEGIN
  IF public.condomit_current_user_type() NOT IN ('porteiro','sindico','síndico','admin','administradora') THEN
    RAISE EXCEPTION 'Sem permissão.' USING ERRCODE='42501';
  END IF;
  FOR p IN
    SELECT * FROM public.packages
    WHERE public.condomit_can_access_cep(cep)
      AND status = 'Aguardando retirada'
      AND received_at <= NOW() - INTERVAL '3 days'
      AND overdue_notified_at IS NULL
  LOOP
    INSERT INTO public.notifications(cep,category,title,description,recipient_email,event_type,event_key,created_at)
    VALUES(p.cep,'Entregas','Encomenda aguardando retirada',
      'Sua encomenda está na portaria há mais de 3 dias. Código de retirada: ' || COALESCE(p.pickup_code,'--'),
      LOWER(p.recipient_email),'package_overdue','package_overdue:'||p.id::TEXT,NOW())
    ON CONFLICT (event_key) DO NOTHING;
    UPDATE public.packages SET overdue_notified_at = NOW() WHERE id = p.id;
    notified := notified + 1;
  END LOOP;
  RETURN notified;
END;
$$;

-- ------------------------------------------------------------
-- 11. RLS
-- ------------------------------------------------------------
ALTER TABLE public.management_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.management_company_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.managed_condominiums ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS management_company_users_self ON public.management_company_users;
CREATE POLICY management_company_users_self ON public.management_company_users
FOR SELECT TO authenticated USING (LOWER(user_email) = public.condomit_auth_email());

DROP POLICY IF EXISTS management_companies_member_select ON public.management_companies;
CREATE POLICY management_companies_member_select ON public.management_companies
FOR SELECT TO authenticated USING (EXISTS (
  SELECT 1 FROM public.management_company_users mcu
  WHERE mcu.company_id = management_companies.id
    AND LOWER(mcu.user_email) = public.condomit_auth_email()
));

DROP POLICY IF EXISTS managed_condominiums_member_select ON public.managed_condominiums;
CREATE POLICY managed_condominiums_member_select ON public.managed_condominiums
FOR SELECT TO authenticated USING (EXISTS (
  SELECT 1 FROM public.management_company_users mcu
  WHERE mcu.company_id = managed_condominiums.company_id
    AND LOWER(mcu.user_email) = public.condomit_auth_email()
));

-- Helper para criar políticas uniformes nas tabelas com coluna cep.
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'condominium_documents','financial_entries','budget_plans','utility_readings','condominium_assets',
    'maintenance_templates','service_tickets','parking_spaces','ev_chargers','ev_charger_bookings',
    'emergency_alerts','communication_reads','condominium_calendar_events','assembly_tasks',
    'audit_log','role_permissions','satisfaction_surveys','satisfaction_responses','engagement_badges',
    'lost_found_matches','wall_comments','wall_reactions'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', tbl || '_select_024', tbl);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (public.condomit_can_access_cep(cep))', tbl || '_select_024', tbl);
  END LOOP;
END $$;

-- Regras de leitura sensíveis e visibilidade dos documentos. As policies
-- genéricas acima são substituídas nestes casos para que esconder a seção
-- na interface não seja a única barreira de segurança.
DROP POLICY IF EXISTS condominium_documents_select_024 ON public.condominium_documents;
CREATE POLICY condominium_documents_select_024 ON public.condominium_documents FOR SELECT TO authenticated
USING (public.condomit_can_access_cep(cep) AND (
  public.condomit_can_manage_cep(cep) OR visibility = 'todos'
  OR (visibility = 'moradores' AND public.condomit_current_user_type() = 'morador')
  OR (visibility = 'portaria' AND public.condomit_current_user_type() = 'porteiro')
));

DROP POLICY IF EXISTS financial_entries_select_024 ON public.financial_entries;
CREATE POLICY financial_entries_select_024 ON public.financial_entries FOR SELECT TO authenticated
USING (public.condomit_has_permission(cep, 'ver_financeiro'));

DROP POLICY IF EXISTS budget_plans_select_024 ON public.budget_plans;
CREATE POLICY budget_plans_select_024 ON public.budget_plans FOR SELECT TO authenticated
USING (public.condomit_has_permission(cep, 'ver_financeiro'));

DROP POLICY IF EXISTS utility_readings_select_024 ON public.utility_readings;
CREATE POLICY utility_readings_select_024 ON public.utility_readings FOR SELECT TO authenticated
USING (public.condomit_can_manage_cep(cep));

DROP POLICY IF EXISTS maintenance_templates_select_024 ON public.maintenance_templates;
CREATE POLICY maintenance_templates_select_024 ON public.maintenance_templates FOR SELECT TO authenticated
USING (public.condomit_can_manage_cep(cep) OR public.condomit_has_permission(cep, 'gerenciar_manutencao'));

DROP POLICY IF EXISTS role_permissions_select_024 ON public.role_permissions;
CREATE POLICY role_permissions_select_024 ON public.role_permissions FOR SELECT TO authenticated
USING (public.condomit_can_manage_cep(cep));

DROP POLICY IF EXISTS service_tickets_select_024 ON public.service_tickets;
CREATE POLICY service_tickets_select_024 ON public.service_tickets FOR SELECT TO authenticated
USING (public.condomit_can_manage_cep(cep) OR LOWER(requester_email) = public.condomit_auth_email());

DROP POLICY IF EXISTS communication_reads_select_024 ON public.communication_reads;
CREATE POLICY communication_reads_select_024 ON public.communication_reads FOR SELECT TO authenticated
USING (public.condomit_can_manage_cep(cep) OR LOWER(user_email) = public.condomit_auth_email());

DROP POLICY IF EXISTS satisfaction_responses_select_024 ON public.satisfaction_responses;
CREATE POLICY satisfaction_responses_select_024 ON public.satisfaction_responses FOR SELECT TO authenticated
USING (public.condomit_can_manage_cep(cep) OR LOWER(user_email) = public.condomit_auth_email());

-- Gestão: CRUD administrativo.
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'condominium_documents','financial_entries','budget_plans','utility_readings','condominium_assets',
    'maintenance_templates','parking_spaces','ev_chargers','emergency_alerts',
    'condominium_calendar_events','assembly_tasks','role_permissions','satisfaction_surveys',
    'lost_found_matches','wall_comments','wall_reactions'
  ] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', tbl || '_insert_024', tbl);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', tbl || '_update_024', tbl);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', tbl || '_delete_024', tbl);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (public.condomit_can_manage_cep(cep))', tbl || '_insert_024', tbl);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING (public.condomit_can_manage_cep(cep)) WITH CHECK (public.condomit_can_manage_cep(cep))', tbl || '_update_024', tbl);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING (public.condomit_can_manage_cep(cep))', tbl || '_delete_024', tbl);
  END LOOP;
END $$;

-- Chamados: qualquer membro cria; dono ou gestão atualiza/consulta.
DROP POLICY IF EXISTS service_tickets_insert_024 ON public.service_tickets;
CREATE POLICY service_tickets_insert_024 ON public.service_tickets FOR INSERT TO authenticated
WITH CHECK (public.condomit_can_access_cep(cep) AND LOWER(requester_email) = public.condomit_auth_email());
DROP POLICY IF EXISTS service_tickets_update_024 ON public.service_tickets;
CREATE POLICY service_tickets_update_024 ON public.service_tickets FOR UPDATE TO authenticated
USING (public.condomit_can_manage_cep(cep) OR LOWER(requester_email) = public.condomit_auth_email())
WITH CHECK (public.condomit_can_manage_cep(cep) OR LOWER(requester_email) = public.condomit_auth_email());

-- Reservas de carregador: membro cria e gerencia a própria reserva; gestão gerencia todas.
DROP POLICY IF EXISTS ev_charger_bookings_insert_024 ON public.ev_charger_bookings;
CREATE POLICY ev_charger_bookings_insert_024 ON public.ev_charger_bookings FOR INSERT TO authenticated
WITH CHECK (public.condomit_can_access_cep(cep) AND LOWER(user_email) = public.condomit_auth_email());
DROP POLICY IF EXISTS ev_charger_bookings_update_024 ON public.ev_charger_bookings;
CREATE POLICY ev_charger_bookings_update_024 ON public.ev_charger_bookings FOR UPDATE TO authenticated
USING (public.condomit_can_manage_cep(cep) OR LOWER(user_email) = public.condomit_auth_email())
WITH CHECK (public.condomit_can_manage_cep(cep) OR LOWER(user_email) = public.condomit_auth_email());
DROP POLICY IF EXISTS ev_charger_bookings_delete_024 ON public.ev_charger_bookings;
CREATE POLICY ev_charger_bookings_delete_024 ON public.ev_charger_bookings FOR DELETE TO authenticated
USING (public.condomit_can_manage_cep(cep) OR LOWER(user_email) = public.condomit_auth_email());

-- Leituras/acknowledgements pessoais.
DROP POLICY IF EXISTS communication_reads_insert_024 ON public.communication_reads;
CREATE POLICY communication_reads_insert_024 ON public.communication_reads FOR INSERT TO authenticated
WITH CHECK (public.condomit_can_access_cep(cep) AND LOWER(user_email) = public.condomit_auth_email());
DROP POLICY IF EXISTS communication_reads_update_024 ON public.communication_reads;
CREATE POLICY communication_reads_update_024 ON public.communication_reads FOR UPDATE TO authenticated
USING (LOWER(user_email) = public.condomit_auth_email()) WITH CHECK (LOWER(user_email) = public.condomit_auth_email());

-- Respostas de satisfação: uma por usuário/pesquisa.
DROP POLICY IF EXISTS satisfaction_responses_insert_024 ON public.satisfaction_responses;
CREATE POLICY satisfaction_responses_insert_024 ON public.satisfaction_responses FOR INSERT TO authenticated
WITH CHECK (public.condomit_can_access_cep(cep) AND LOWER(user_email) = public.condomit_auth_email());
DROP POLICY IF EXISTS satisfaction_responses_update_024 ON public.satisfaction_responses;
CREATE POLICY satisfaction_responses_update_024 ON public.satisfaction_responses FOR UPDATE TO authenticated
USING (LOWER(user_email) = public.condomit_auth_email()) WITH CHECK (LOWER(user_email) = public.condomit_auth_email());

-- Auditoria: usuário pode inserir eventos próprios; só gestão lê (select já limita CEP, reforço de leitura abaixo).
DROP POLICY IF EXISTS audit_log_insert_024 ON public.audit_log;
CREATE POLICY audit_log_insert_024 ON public.audit_log FOR INSERT TO authenticated
WITH CHECK (public.condomit_can_access_cep(cep) AND LOWER(actor_email) = public.condomit_auth_email());
DROP POLICY IF EXISTS audit_log_select_024 ON public.audit_log;
CREATE POLICY audit_log_select_024 ON public.audit_log FOR SELECT TO authenticated
USING (public.condomit_can_manage_cep(cep));

-- Badges: leitura pelo condomínio; escrita apenas gestão.
DROP POLICY IF EXISTS engagement_badges_insert_024 ON public.engagement_badges;
CREATE POLICY engagement_badges_insert_024 ON public.engagement_badges FOR INSERT TO authenticated
WITH CHECK (public.condomit_can_manage_cep(cep));
DROP POLICY IF EXISTS engagement_badges_update_024 ON public.engagement_badges;
CREATE POLICY engagement_badges_update_024 ON public.engagement_badges FOR UPDATE TO authenticated
USING (public.condomit_can_manage_cep(cep)) WITH CHECK (public.condomit_can_manage_cep(cep));
DROP POLICY IF EXISTS engagement_badges_delete_024 ON public.engagement_badges;
CREATE POLICY engagement_badges_delete_024 ON public.engagement_badges FOR DELETE TO authenticated
USING (public.condomit_can_manage_cep(cep));

-- Feed: comentários/reactions pertencem ao usuário; gestão pode moderar comentários.
DROP POLICY IF EXISTS wall_comments_insert_024 ON public.wall_comments;
CREATE POLICY wall_comments_insert_024 ON public.wall_comments FOR INSERT TO authenticated
WITH CHECK (public.condomit_can_access_cep(cep) AND LOWER(user_email)=public.condomit_auth_email());
DROP POLICY IF EXISTS wall_comments_delete_024 ON public.wall_comments;
CREATE POLICY wall_comments_delete_024 ON public.wall_comments FOR DELETE TO authenticated
USING (LOWER(user_email)=public.condomit_auth_email() OR public.condomit_can_manage_cep(cep));
DROP POLICY IF EXISTS wall_reactions_insert_024 ON public.wall_reactions;
CREATE POLICY wall_reactions_insert_024 ON public.wall_reactions FOR INSERT TO authenticated
WITH CHECK (public.condomit_can_access_cep(cep) AND LOWER(user_email)=public.condomit_auth_email());
DROP POLICY IF EXISTS wall_reactions_update_024 ON public.wall_reactions;
CREATE POLICY wall_reactions_update_024 ON public.wall_reactions FOR UPDATE TO authenticated
USING (LOWER(user_email)=public.condomit_auth_email()) WITH CHECK (LOWER(user_email)=public.condomit_auth_email());
DROP POLICY IF EXISTS wall_reactions_delete_024 ON public.wall_reactions;
CREATE POLICY wall_reactions_delete_024 ON public.wall_reactions FOR DELETE TO authenticated
USING (LOWER(user_email)=public.condomit_auth_email());

ALTER TABLE public.user_session_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_session_log_select_024 ON public.user_session_log;
CREATE POLICY user_session_log_select_024 ON public.user_session_log FOR SELECT TO authenticated
USING (LOWER(user_email)=public.condomit_auth_email());
DROP POLICY IF EXISTS user_session_log_insert_024 ON public.user_session_log;
CREATE POLICY user_session_log_insert_024 ON public.user_session_log FOR INSERT TO authenticated
WITH CHECK (LOWER(user_email)=public.condomit_auth_email());
DROP POLICY IF EXISTS user_session_log_update_024 ON public.user_session_log;
CREATE POLICY user_session_log_update_024 ON public.user_session_log FOR UPDATE TO authenticated
USING (LOWER(user_email)=public.condomit_auth_email()) WITH CHECK (LOWER(user_email)=public.condomit_auth_email());
DROP POLICY IF EXISTS user_session_log_delete_024 ON public.user_session_log;
CREATE POLICY user_session_log_delete_024 ON public.user_session_log FOR DELETE TO authenticated
USING (LOWER(user_email)=public.condomit_auth_email());

-- Favoritos de marketplace.
ALTER TABLE public.marketplace_favorites ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS marketplace_favorites_select_024 ON public.marketplace_favorites;
CREATE POLICY marketplace_favorites_select_024 ON public.marketplace_favorites FOR SELECT TO authenticated
USING (LOWER(user_email) = public.condomit_auth_email());
DROP POLICY IF EXISTS marketplace_favorites_insert_024 ON public.marketplace_favorites;
CREATE POLICY marketplace_favorites_insert_024 ON public.marketplace_favorites FOR INSERT TO authenticated
WITH CHECK (LOWER(user_email) = public.condomit_auth_email() AND EXISTS (
  SELECT 1 FROM public.marketplace_items mi
  WHERE mi.id = marketplace_favorites.item_id
    AND public.condomit_can_access_cep(mi.cep)
));
DROP POLICY IF EXISTS marketplace_favorites_delete_024 ON public.marketplace_favorites;
CREATE POLICY marketplace_favorites_delete_024 ON public.marketplace_favorites FOR DELETE TO authenticated
USING (LOWER(user_email) = public.condomit_auth_email());

-- Permite administradora ler condomínios vinculados mesmo sem vínculo em user_condominiums.
DROP POLICY IF EXISTS managed_condominiums_member_select ON public.managed_condominiums;
CREATE POLICY managed_condominiums_member_select ON public.managed_condominiums FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.management_company_users mcu
  WHERE mcu.company_id = managed_condominiums.company_id
    AND LOWER(mcu.user_email) = public.condomit_auth_email()
));

-- Auditoria automática dos módulos críticos.
CREATE OR REPLACE FUNCTION public.condomit_audit_row_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE data JSONB; target_cep TEXT; target_id TEXT;
BEGIN
  data := CASE WHEN TG_OP = 'DELETE' THEN TO_JSONB(OLD) ELSE TO_JSONB(NEW) END;
  target_cep := COALESCE(data->>'cep', data->>'condominium_cep');
  target_id := COALESCE(data->>'id', data->>'email', '');
  IF COALESCE(target_cep,'') <> '' AND public.condomit_auth_email() <> '' THEN
    INSERT INTO public.audit_log(cep,actor_email,action,entity_type,entity_id,details)
    VALUES(target_cep,public.condomit_auth_email(),LOWER(TG_OP),TG_TABLE_NAME,target_id,JSONB_BUILD_OBJECT('operation',TG_OP));
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DO $$
DECLARE tbl TEXT; trigger_name TEXT;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'condominium_documents','financial_entries','budget_plans','utility_readings','condominium_assets',
    'maintenance_templates','service_tickets','parking_spaces','ev_chargers','ev_charger_bookings',
    'emergency_alerts','condominium_calendar_events','assembly_tasks','role_permissions',
    'satisfaction_surveys','engagement_badges','marketplace_items','lost_and_found_items','packages',
    'condominium_notices','scheduled_assemblies'
  ] LOOP
    trigger_name := 'trg_condomit_audit_' || tbl;
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', trigger_name, tbl);
    EXECUTE format('CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.condomit_audit_row_change()', trigger_name, tbl);
  END LOOP;
END $$;

-- Grants.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.condominium_documents, public.financial_entries, public.budget_plans, public.utility_readings, public.condominium_assets, public.maintenance_templates, public.service_tickets, public.parking_spaces, public.ev_chargers, public.ev_charger_bookings, public.emergency_alerts, public.communication_reads, public.condominium_calendar_events, public.assembly_tasks, public.audit_log, public.role_permissions, public.satisfaction_surveys, public.satisfaction_responses, public.engagement_badges, public.marketplace_favorites, public.lost_found_matches, public.wall_comments, public.wall_reactions, public.user_session_log TO authenticated;
GRANT SELECT ON public.management_companies, public.management_company_users, public.managed_condominiums TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_is_management_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_admin_manages_cep(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_can_access_cep(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_can_manage_cep(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_managed_condominiums_dashboard() TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_has_permission(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_generate_due_maintenance() TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_set_notice_options(BIGINT, BOOLEAN, BOOLEAN, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_notify_old_packages() TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_expire_marketplace_items() TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_archive_old_lost_found() TO authenticated;
GRANT EXECUTE ON FUNCTION public.condomit_suggest_lost_found_matches() TO authenticated;

COMMIT;
