-- ============================================================
-- 037 - Registro de atividade oral da assembleia
-- Permite que a ata diferencie "ninguém falou" de
-- "houve fala, mas o navegador não forneceu texto transcrito".
-- ============================================================

CREATE TABLE IF NOT EXISTS public.assembly_speech_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assembly_id BIGINT NOT NULL REFERENCES public.scheduled_assemblies(id) ON DELETE CASCADE,
  cep TEXT NOT NULL REFERENCES public.condominiums(cep) ON UPDATE CASCADE ON DELETE CASCADE,
  participant_email TEXT NOT NULL,
  participant_name TEXT NOT NULL,
  participant_role TEXT,
  participant_identity TEXT,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ NOT NULL,
  duration_seconds NUMERIC(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT assembly_speech_activity_duration_check CHECK (duration_seconds >= 0),
  CONSTRAINT assembly_speech_activity_time_check CHECK (ended_at >= started_at)
);

CREATE INDEX IF NOT EXISTS idx_assembly_speech_activity_assembly_time
  ON public.assembly_speech_activity(assembly_id, started_at ASC);

CREATE INDEX IF NOT EXISTS idx_assembly_speech_activity_participant
  ON public.assembly_speech_activity(assembly_id, participant_email);

ALTER TABLE public.assembly_speech_activity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS assembly_speech_activity_select_037 ON public.assembly_speech_activity;
CREATE POLICY assembly_speech_activity_select_037
ON public.assembly_speech_activity
FOR SELECT TO authenticated
USING (public.condomit_user_belongs_to_cep(cep));

-- Inserções são feitas exclusivamente pela RPC abaixo para que um usuário
-- não consiga registrar fala em nome de outra pessoa.
REVOKE INSERT, UPDATE, DELETE ON public.assembly_speech_activity FROM authenticated;
GRANT SELECT ON public.assembly_speech_activity TO authenticated;

DROP FUNCTION IF EXISTS public.condomit_log_assembly_speech_activity(BIGINT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ);
CREATE OR REPLACE FUNCTION public.condomit_log_assembly_speech_activity(
  target_assembly_id BIGINT,
  participant_identity_value TEXT DEFAULT NULL,
  started_at_value TIMESTAMPTZ DEFAULT NOW(),
  ended_at_value TIMESTAMPTZ DEFAULT NOW()
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  caller_email TEXT := public.condomit_auth_email();
  caller_name TEXT;
  caller_role TEXT;
  assembly_row public.scheduled_assemblies%ROWTYPE;
  saved_row public.assembly_speech_activity%ROWTYPE;
  normalized_start TIMESTAMPTZ := COALESCE(started_at_value, NOW());
  normalized_end TIMESTAMPTZ := COALESCE(ended_at_value, NOW());
  seconds_spoken NUMERIC(10,2);
BEGIN
  IF caller_email = '' THEN
    RAISE EXCEPTION 'Sessão inválida.' USING ERRCODE = '42501';
  END IF;

  SELECT sa.* INTO assembly_row
  FROM public.scheduled_assemblies sa
  WHERE sa.id = target_assembly_id
  LIMIT 1;

  IF NOT FOUND OR NOT public.condomit_user_belongs_to_cep(assembly_row.cep) THEN
    RAISE EXCEPTION 'Assembleia não encontrada neste condomínio.' USING ERRCODE = '42501';
  END IF;

  IF normalized_end < normalized_start THEN
    normalized_end := normalized_start;
  END IF;

  -- Limita um único trecho a 10 minutos. Se houver fala mais longa, o cliente
  -- continuará gerando novos intervalos conforme o detector de voz mudar.
  IF normalized_end > normalized_start + INTERVAL '10 minutes' THEN
    normalized_end := normalized_start + INTERVAL '10 minutes';
  END IF;

  seconds_spoken := ROUND(EXTRACT(EPOCH FROM (normalized_end - normalized_start))::NUMERIC, 2);
  IF seconds_spoken < 0.70 THEN
    RETURN jsonb_build_object('skipped', true, 'reason', 'too_short');
  END IF;

  SELECT COALESCE(NULLIF(BTRIM(u.name), ''), caller_email), LOWER(COALESCE(u.user_type, 'morador'))
    INTO caller_name, caller_role
  FROM public.users u
  WHERE LOWER(COALESCE(u.email, '')) = caller_email
  LIMIT 1;

  INSERT INTO public.assembly_speech_activity (
    assembly_id,
    cep,
    participant_email,
    participant_name,
    participant_role,
    participant_identity,
    started_at,
    ended_at,
    duration_seconds
  ) VALUES (
    assembly_row.id,
    assembly_row.cep,
    caller_email,
    COALESCE(caller_name, caller_email),
    COALESCE(caller_role, 'morador'),
    NULLIF(BTRIM(COALESCE(participant_identity_value, '')), ''),
    normalized_start,
    normalized_end,
    seconds_spoken
  )
  RETURNING * INTO saved_row;

  RETURN to_jsonb(saved_row);
END;
$$;

REVOKE ALL ON FUNCTION public.condomit_log_assembly_speech_activity(BIGINT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.condomit_log_assembly_speech_activity(BIGINT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO authenticated;

DO $$
BEGIN
  IF to_regclass('public.assembly_speech_activity_id_seq') IS NOT NULL THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.assembly_speech_activity_id_seq TO authenticated';
  END IF;
END $$;
