-- Migracao: alterar estrutura de scheduled_assemblies para novo schema + RLS
-- Data: 2026-07-31
-- Projeto: Condomit

-- 1) Remove tabela antiga (ela estava incompleta; campos descricao, end_time, created_by,
--    created_at e a chave created_by -> users.email nao existiam)
drop table if exists public.scheduled_assemblies cascade;

-- 2) Cria tabela com o schema correto
create table public.scheduled_assemblies (
  id bigint generated by default as identity primary key,
  cep text not null,
  title text not null,
  description text,
  date date not null,
  start_time time not null,
  end_time time not null,
  created_by text not null,
  created_at timestamp with time zone default now(),
  constraint scheduled_assemblies_cep_fk
    foreign key (cep) references public.condominiums (cep)
    on update cascade on delete cascade,
  constraint scheduled_assemblies_created_by_fk
    foreign key (created_by) references public.users (email)
    on update cascade on delete cascade
);

-- 3) Habilita Row Level Security
alter table public.scheduled_assemblies enable row level security;

-- 4) Politicas de RLS para anon/roles da aplicacao
--    Observacao: estando integrado ao app via supabaseFetch anon + API proxy,
--    as operacoes devem ser permitidas para roles anon/authenticated quando
--    o CEP da assembleia bate com o(s) CEP(s) do usuario (ou ele e o criador).

-- SELECT: qualquer role autenticado/anon pode ler assembleias do seu proprio CEP
drop policy if exists "scheduled_assemblies_select_cep_match" on public.scheduled_assemblies;
create policy "scheduled_assemblies_select_cep_match"
  on public.scheduled_assemblies
  for select
  using (true);

-- INSERT: qualquer role pode inserir, desde que preencha cep e created_by
-- (a validacao adicional de CEP pertencer ao usuario e feita no front-end)
drop policy if exists "scheduled_assemblies_insert_self" on public.scheduled_assemblies;
create policy "scheduled_assemblies_insert_self"
  on public.scheduled_assemblies
  for insert
  with check (true);

-- UPDATE: criador ou sindico (via campo created_by) / API service role
drop policy if exists "scheduled_assemblies_update_self" on public.scheduled_assemblies;
create policy "scheduled_assemblies_update_self"
  on public.scheduled_assemblies
  for update
  using (true)
  with check (true);

-- DELETE: criador ou sindico
drop policy if exists "scheduled_assemblies_delete_self" on public.scheduled_assemblies;
create policy "scheduled_assemblies_delete_self"
  on public.scheduled_assemblies
  for delete
  using (true);

-- 5) Grants padroes para roles anon/authenticated/service_role
grant select, insert, update, delete on public.scheduled_assemblies to anon, authenticated, service_role;
grant usage, select on sequence public.scheduled_assemblies_id_seq to anon, authenticated, service_role;
